mutation UpdateBusiness(
  $data: BusinessUpdateInput!
  $where: BusinessWhereUniqueInput!
) {
  updateBusiness(data: $data, where: $where) {
    id
    name
    siteNumber
    fullName
    publicName
    demId
    parent {
      id
      name
      fullName
      publicName
    }
    locations {
      id
      building
      street
      townCity
      county
      postcode
      county
      geoLng
      geoLat
      full
    }
    groups {
      id
      name
    }
    tags {
      id
      name
    }
    totalUsers
    currency
  }
}
