query IncidentMap($where: IncidentWhereInput!) {
  incidents(where: $where) {
    id
    subject
    reference
    policeRef
    customerRef
    dayTime
    description
    priority
    approved
    totalValue
    location {
      id
      geoLat
      geoLng
      full
    }
    business {
      id
      name
    }
    images {
      id
      optimised
      url
    }
    crimeTypes {
      id
      name
    }
    groups {
      id
      name
    }
    offenders {
      id
      name
    }
    createdBy {
      id
      fullName
    }
  }
}
