mutation createUserChat($data: UserChatCreateInput!) {
  createUserChat(data: $data) {
          id
      newMessages
      mentioned
      updatedAt
      createdAt
      user {
        id
        fullName
        firstLetter
        origFirstLetter
        origName
      }
      chat {
        id
        name
        firstLetter
        totalMembers
        messages(first: 1, orderBy: [{ createdAt: desc }]) {
          id
          content
          createdAt
          from {
            id
            fullName
            origFirstLetter
            origName
            firstLetter
          }
          images {
            id
            url
            optimised
            position
          }
          incidents {
            id
            subject
          }
          offenders {
            id
            name
          }
          vehicles {
            id
            reference
          }
          crimeGroups {
            id
            reference
          }
        }
      }
  }
}
