query Checklist($where: ChecklistWhereUniqueInput!) {
  checklist(where: $where) {
    id
    title
    description
    sections {
      order
      title
      dependsOnWeight {
        weight
        dependsOn
      }
      subsections {
        title
        order
        questions {
          order
          question
          type
          dependent
          brandIds
          weight {
            weight
            answer
          }
        }
      }
    }
    users {
      id
    }
    roles {
      id
    }
    groups {
      id
    }
    business {
      id
    }
  }
}
