query ChatMessages($where: ChatMessagesWhereInput!, $take: Int, $skip: Int) {
  chatMessages(where: $where, take: $take, skip: $skip) {
    id
    content
    createdAt
    currentUser
    formattedDateTime
    from {
      id
      fullName
      origName
      origFirstLetter
      firstLetter
    }
    sent
    showUser
    paddingTop
    type
    images {
      id
      url
      optimised
    }
    crimeGroups {
      totalOffenders
      totalIncidents
      alias
      id
      reference
      totalRecoveredValue
      totalTheftSuccess
      totalValue
      updatedAt
    }
    vehicles {
      updatedAt
      totalOffenders
      registration
      reference
      model
      make
      id
      colour
      images {
        id
        optimised
        url
      }
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
      }
    }
    offenders {
      id
      updatedAt
      age
      build
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
      }
    }
  }
}
