query messages($chat: String, $after: MessageWhereUniqueInput) {
  messages(
    where: { chat: { id: { equals: $chat } } }
    first: 30
    orderBy: { createdAt: asc }
    after: $after
  ) {
    id
    sent
    from {
      id
      fullName
      organisation
    }
    chat {
      id
      name
    }
    content
    createdAt
    images {
      id
      url
      optimised
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
      }
    }
    offenders {
      id
      age
      build
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
      }
    }
  }
}
