query messages($chat: String, $before: MessageWhereUniqueInput) {
  messages(
    where: { chat: { id: { equals: $chat } } }
    last: 30
    orderBy: { createdAt: asc }
    before: $before
  ) {
    id
    sent
    from {
      id
      fullName
      businesses {
        id
        name
      }
    }
    chat {
      id
      name
    }
    content
    createdAt
    images {
      id
      url
      position
      rotation
      optimised
    }
    crimeGroups {
      totalOffenders
      totalIncidents
      alias
      id
      reference
      totalRecoveredValue
      totalTheftSuccess
      totalValue
      updatedAt
    }
    vehicles {
      updatedAt
      totalOffenders
      registration
      reference
      model
      make
      id
      colour
      images {
        id
        optimised
        position
        rotation
        url
      }
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
        position
        rotation
      }
    }
    offenders {
      id
      updatedAt
      age
      build
      height
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
        position
        rotation
      }
    }
  }
}
