query currentUser($scheme: UniqueId) {
  currentUser {
    id
    fullName
    origName
    email
    reference
    demId
    publicName
    reportToAllBusinesses
    notificationCount(scheme: $scheme)
    messageCount
    defaultScheme
    businesses {
      id
      name
      fullName
      demId
      brands
    }
    newUser
    groups {
      id
      name
      scheme {
        id
      }
    }
    defaultGroups {
      id
      name
      scheme {
        id
      }
    }
    schemes {
      id
      role
      scheme {
        customTranslations
        logo {
          optimisedPersisted
        }
        darkLogo {
          optimisedPersisted
        }
        userTodos
        id
        name
        goodsMode
        autoApproveIncidents
        autoApproveOffenders
        defaultPublicOffenderDOB
        restrictIncidentAccess
        reportOnly
        facialRecognition
        imagesRequiredOnOffenders
        taskTimeTracking
        languageCount
        autoPopulateDescription
        needJustification
        requireSiteNumberForUsers
      }
      permissions {
        model
        allowedMethods
      }
    }
    incidentEmail
    incidentPush
    offenderEmail
    offenderPush
    bulletinEmails
    bulletinPush
    messagePush
  }
}
