query currentUser {
  currentUser {
    id
    fullName
    email
    organisation
    newUser
    groups {
      id
      name
    }
    schemes {
      id
      role
      scheme {
        id
        name
        autoApproveIncidents
        autoApproveOffenders
      }
    }
    addresses(where: { primary: { equals: true } }) {
      id
      building
      street
      townCity
      county
      postcode
    }
    incidentEmail
    incidentPush
    offenderEmail
    offenderPush
    messagePush
  }
}
