query currentUser($scheme: UniqueId) {
  currentUser {
    id
    fullName
    origName
    email
    reference
    demId
    publicName
    reportToAllBusinesses
    notificationCount(scheme: $scheme)
    businesses {
      id
      name
      fullName
      demId
    }
    newUser
    groups {
      id
      name
      scheme {
        id
      }
    }
    schemes {
      id
      role
      scheme {
        customTranslations
        logo {
          optimisedPersisted
        }
        darkLogo {
          optimisedPersisted
        }
        userTodos
        id
        name
        goodsMode
        autoApproveIncidents
        autoApproveOffenders
        defaultPublicOffenderDOB
        restrictIncidentAccess
        facialRecognition
        imagesRequiredOnOffenders
        taskTimeTracking
      }
    }
    incidentEmail
    incidentPush
    offenderEmail
    offenderPush
    messagePush
  }
}
