query User(
  $where: UserWhereUniqueInput!
  $groupWhere: GroupWhereInput
  $chatWhere: UserChatWhereInput
  $schemeWhere: UserSchemeWhereInput
) {
  user(where: $where) {
    id
    fullName
    email
    status
    demId
    publicName
    reportToAllBusinesses
    businesses {
      id
      name
      fullName
      demId
    }
    disabled
    newUser
    incidentEmail
    incidentPush
    subscribedIncidentOnly
    subscribedOffenderOnly
    messagePush
    offenderEmail
    offenderPush
    signedTerms {
      id
      signature
      terms {
        id
        version
      }
    }
    groups(where: $groupWhere) {
      id
      name
    }
    approverGroups {
      id
      name
    }
    chats(where: $chatWhere) {
      id
      chat {
        id
        name
      }
    }
    schemes(where: $schemeWhere) {
      id
      schemeId
      role
    }
    totalLastYearLogin
    totalThirtyDaysLogin
    lastTenLogin {
      loginTime
      id
    }
    lastLogin {
      loginTime
      id
    }
  }
}
