query listTodos(
  $where: TodoWhereInput
  $take: Int
  $skip: Int
  $orderBy: [TodoOrderBy!]
) {
  listTodos(where: $where, orderBy: $orderBy, take: $take, skip: $skip) {
    todos {
      description
      id
      name
      dueDate
      completed
      type
      vehicleId
      offenderId
      crimeGroupId
      incidentId
      investigationId
      chatId
      similarOffenderIds
      completedDate
      createdBy {
        id
        fullName
      }
      completedBy {
        id
        fullName
      }
      assignedUsers {
        id
        fullName
      }
    }
    total
    uncompletedTotal
    totalUserTodos
  }
}
