query listTodos(
  $where: TodoWhereInput
  $take: Int
  $skip: Int
  $orderBy: [TodoOrderBy!]
) {
  listTodos(where: $where, orderBy: $orderBy, take: $take, skip: $skip) {
    todos {
      description
      id
      name
      dueDate
      createdAt
      completed
      authorised
      type
      vehicleId
      vehicle {
        id
        reference
      }
      offenderId
      offender {
        id
        reference
      }
      crimeGroupId
      crimeGroup {
        id
        reference
      }
      incidentId
      incident {
        id
        reference
      }
      investigationId
      investigation {
        id
        reference
      }
      chatId
      completedDate
      createdBy {
        id
        fullName
      }
      completedBy {
        id
        fullName
      }
      assignedUsers {
        id
        fullName
      }
      groups {
        id
        name
      }
    }
    total
    uncompletedTotal
    totalUserTodos
  }
}
