mutation UpdateStockRemovalRequest($where: UniqueId!, $data: UpdateStockRemovalRequestInput!) {
    updateStockRemovalRequest(where: $where, data: $data) {
        id
        createdAt
        title
        description
        status
        reference
        costCentreCode
        destination
        nominalCode
        fascia
        picker {
            id
            fullName
        }
        priority
        personalityInfluences
        reason
        reasonForNonReturn
        rechargeBrand
        rechargeReference
        recipientEmail
        recipientName
        recipientPhone
        returnDate
        shippingAddress
        shippingAddressLine1
        shippingAddressLine2
        shippingCity
        shippingCounty
        shippingPostcode
        shippingCountry
        smqAccountNumber
        socialHandles
        storeOrDC
        willStockBeReturned
        items {
            id
            name
            requestedQuantity
            pickedQuantity
            pickLocation
        }
        business {
            id
            name
        }
        approvers {
            status
            id
            user {
                id
                fullName
            }
        }
    }
}
