query ResourceTrainingVideos(
  $schemeId: String!
  $where: TrainingVideoWhereInput
  $take: Int
  $skip: Int
  $orderBy: [TrainingVideoOrderByInput!]
) {
  trainingVideos(
    schemeId: $schemeId
    where: $where
    take: $take
    skip: $skip
    orderBy: $orderBy
  ) {
    id
    title
    description
    videoUrl
    thumbnailUrl
    thumbnailStatus
    viewCount
    tags {
      id
      name
    }
    groups {
      id
      name
    }
    loginPrompt
    mandatory
    createdAt
    updatedAt
  }
}
