import React from 'react';

import View from './PerformanceReport.view';
import usePerformanceReport from './hooks/usePerformanceReport';

const PerformanceReport = (): JSX.Element => {
  const {
    addLogo,
    addLogoDrawer,
    businessContributionCurrentPage,
    businessContributionPageSize,
    businessContributionSortDirection,
    businessContributionSortField,
    businessContributionTableData,
    businessContributionTotal,
    changeSize,
    componentRef,
    crimeGroupPerformanceTableData,
    currentPage,
    data,
    dateRange,
    editMode,
    errors,
    filterCount,
    filtersOpen,
    getBusinessContributionSortIndicator,
    getSortIndicator,
    getTargetedBusinessSortIndicator,
    groups,
    groupsLoading,
    handleBusinessContributionPageChange,
    handleBusinessContributionSort,
    handlePageChange,
    handlePrint,
    handleSort,
    handleTargetedBusinessPageChange,
    handleTargetedBusinessSort,
    incidentTypeIds,
    investigationsData,
    isPrinting,
    layout,
    loading,
    loadingStates,
    logos,
    metadata,
    minDrawer,
    offendersTableData,
    pageSize,
    redactOnPrint,
    removeItem,
    removeLogo,
    saveAsDrawer,
    saveTemplate,
    saving,
    schemeId,
    selectTemplate,
    selectedBrands,
    selectedBusiness,
    selectedGroups,
    selectedIndustries,
    selectedRoles,
    selectedTemplate,
    setAddLogoDrawer,
    setDateRange,
    setEditMode,
    setIncidentTypeIds,
    setLayout,
    setMetadata,
    setMinDrawer,
    setRedactOnPrint,
    setSaveAsDrawer,
    setSelectedBrands,
    setSelectedBusiness,
    setSelectedGroups,
    setSelectedIndustries,
    setSelectedRoles,
    sortDirection,
    sortField,
    targetedBusinessCurrentPage,
    targetedBusinessData,
    targetedBusinessPageSize,
    targetedBusinessSortDirection,
    targetedBusinessSortField,
    targetedBusinessTotal,
    targetedGoodsData,
    templates,
    toggleFiltersOpen,
    userContributionTableData,
    userContributionsTotal,
    userEngagementLoading,
  } = usePerformanceReport();
  return (
    <View
      addLogo={addLogo}
      addLogoDrawer={addLogoDrawer}
      businessContributionCurrentPage={businessContributionCurrentPage}
      businessContributionPageSize={businessContributionPageSize}
      businessContributionSortDirection={businessContributionSortDirection}
      businessContributionSortField={businessContributionSortField}
      businessContributionTableData={businessContributionTableData}
      businessContributionTotal={businessContributionTotal}
      changeSize={changeSize}
      componentRef={componentRef}
      crimeGroupPerformanceTableData={crimeGroupPerformanceTableData}
      currentPage={currentPage}
      data={data}
      dateRange={dateRange}
      editMode={editMode}
      errors={errors}
      filterCount={filterCount}
      filtersOpen={filtersOpen}
      getBusinessContributionSortIndicator={
        getBusinessContributionSortIndicator
      }
      getSortIndicator={getSortIndicator}
      getTargetedBusinessSortIndicator={getTargetedBusinessSortIndicator}
      groups={groups}
      groupsLoading={groupsLoading}
      handleBusinessContributionPageChange={
        handleBusinessContributionPageChange
      }
      handleBusinessContributionSort={handleBusinessContributionSort}
      handlePageChange={handlePageChange}
      handlePrint={handlePrint}
      handleSort={handleSort}
      handleTargetedBusinessPageChange={handleTargetedBusinessPageChange}
      handleTargetedBusinessSort={handleTargetedBusinessSort}
      incidentTypeIds={incidentTypeIds}
      investigationsData={investigationsData}
      isPrinting={isPrinting}
      layout={layout}
      loading={loading}
      loadingStates={loadingStates}
      logos={logos}
      metadata={metadata}
      minDrawer={minDrawer}
      offendersTableData={offendersTableData}
      pageSize={pageSize}
      redactOnPrint={redactOnPrint}
      removeItem={removeItem}
      removeLogo={removeLogo}
      saveAsDrawer={saveAsDrawer}
      saveTemplate={saveTemplate}
      saving={saving}
      schemeId={schemeId}
      selectTemplate={selectTemplate}
      selectedBrands={selectedBrands}
      selectedBusiness={selectedBusiness}
      selectedGroups={selectedGroups}
      selectedIndustries={selectedIndustries}
      selectedRoles={selectedRoles}
      selectedTemplate={selectedTemplate}
      setAddLogoDrawer={setAddLogoDrawer}
      setDateRange={setDateRange}
      setEditMode={setEditMode}
      setIncidentTypeIds={setIncidentTypeIds}
      setLayout={setLayout}
      setMetadata={setMetadata}
      setMinDrawer={setMinDrawer}
      setRedactOnPrint={setRedactOnPrint}
      setSaveAsDrawer={setSaveAsDrawer}
      setSelectedBrands={setSelectedBrands}
      setSelectedBusiness={setSelectedBusiness}
      setSelectedGroups={setSelectedGroups}
      setSelectedIndustries={setSelectedIndustries}
      setSelectedRoles={setSelectedRoles}
      sortDirection={sortDirection}
      sortField={sortField}
      targetedBusinessCurrentPage={targetedBusinessCurrentPage}
      targetedBusinessData={targetedBusinessData}
      targetedBusinessPageSize={targetedBusinessPageSize}
      targetedBusinessSortDirection={targetedBusinessSortDirection}
      targetedBusinessSortField={targetedBusinessSortField}
      targetedBusinessTotal={targetedBusinessTotal}
      targetedGoodsData={targetedGoodsData}
      templates={templates}
      toggleFiltersOpen={toggleFiltersOpen}
      userContributionTableData={userContributionTableData}
      userContributionsTotal={userContributionsTotal}
      userEngagementLoading={userEngagementLoading}
    />
  );
};

export default PerformanceReport;
