import React from 'react';

import View from './PerformanceReport.view';
import usePerformanceReport from './hooks/usePerformanceReport';

const PerformanceReport = (): JSX.Element => {
  const {
    addLogo,
    addLogoDrawer,
    businessContributionTableData,
    changeSize,
    componentRef,
    crimeGroupPerformanceTableData,
    data,
    dateRange,
    editMode,
    filterCount,
    filtersOpen,
    groups,
    groupsLoading,
    handlePrint,
    incidentTypeIds,
    investigationsData,
    isPrinting,
    layout,
    loading,
    logos,
    metadata,
    minDrawer,
    offendersTableData,
    redactOnPrint,
    removeItem,
    removeLogo,
    saveAsDrawer,
    saveTemplate,
    saving,
    schemeId,
    selectTemplate,
    selectedBrands,
    selectedGroups,
    selectedIndustries,
    selectedRoles,
    selectedTemplate,
    setAddLogoDrawer,
    setDateRange,
    setEditMode,
    setIncidentTypeIds,
    setLayout,
    setMetadata,
    setMinDrawer,
    setRedactOnPrint,
    setSaveAsDrawer,
    setSelectedBrands,
    setSelectedGroups,
    setSelectedIndustries,
    setSelectedRoles,
    targetedBusinessData,
    targetedGoodsData,
    templates,
    toggleFiltersOpen,
    userContributionTableData,
  } = usePerformanceReport();
  return (
    <View
      addLogo={addLogo}
      addLogoDrawer={addLogoDrawer}
      businessContributionTableData={businessContributionTableData}
      changeSize={changeSize}
      componentRef={componentRef}
      crimeGroupPerformanceTableData={crimeGroupPerformanceTableData}
      data={data}
      dateRange={dateRange}
      editMode={editMode}
      filterCount={filterCount}
      filtersOpen={filtersOpen}
      groups={groups}
      groupsLoading={groupsLoading}
      handlePrint={handlePrint}
      incidentTypeIds={incidentTypeIds}
      investigationsData={investigationsData}
      isPrinting={isPrinting}
      layout={layout}
      loading={loading}
      logos={logos}
      metadata={metadata}
      minDrawer={minDrawer}
      offendersTableData={offendersTableData}
      redactOnPrint={redactOnPrint}
      removeItem={removeItem}
      removeLogo={removeLogo}
      saveAsDrawer={saveAsDrawer}
      saveTemplate={saveTemplate}
      saving={saving}
      schemeId={schemeId}
      selectTemplate={selectTemplate}
      selectedBrands={selectedBrands}
      selectedGroups={selectedGroups}
      selectedIndustries={selectedIndustries}
      selectedRoles={selectedRoles}
      selectedTemplate={selectedTemplate}
      setAddLogoDrawer={setAddLogoDrawer}
      setDateRange={setDateRange}
      setEditMode={setEditMode}
      setIncidentTypeIds={setIncidentTypeIds}
      setLayout={setLayout}
      setMetadata={setMetadata}
      setMinDrawer={setMinDrawer}
      setRedactOnPrint={setRedactOnPrint}
      setSaveAsDrawer={setSaveAsDrawer}
      setSelectedBrands={setSelectedBrands}
      setSelectedGroups={setSelectedGroups}
      setSelectedIndustries={setSelectedIndustries}
      setSelectedRoles={setSelectedRoles}
      targetedBusinessData={targetedBusinessData}
      targetedGoodsData={targetedGoodsData}
      templates={templates}
      toggleFiltersOpen={toggleFiltersOpen}
      userContributionTableData={userContributionTableData}
    />
  );
};

export default PerformanceReport;
