query CrimeGroup($where: CrimeGroupWhereUniqueInput!) {
  crimeGroup(where: $where) {
    id
    reference
    totalIncidents
    totalOffenders
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    offenders {
      id
      name
      reference
      lastActive {
        id
        dayTime
      }
      hair
      peculiarities
      race
      dateOfBirth
      dateSource
      build
      age
      gender
      images {
        id
        optimised
      }
      totalTheftSuccess
      totalRecoveredValue
      totalIncidents
      totalValue
    }
    incidents {
      id
      subject
      dayTime
      createdBy {
        id
        organisation
      }
      value
      recoveredValue
      reference
      policeRef
    }
  }
}