import type { ExtendedLayout, MetaData } from '../../types';

export const OffenderMetaData: MetaData[] = [
  { key: 'offenderSummary', type: 'summary' },
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'crimeTypesByBusinessRadial', type: 'radial' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsHeatMap', type: 'table' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
];

const OffenderLayout: ExtendedLayout[] = [
  {
    w: 2,
    h: 1,
    x: 0,
    y: 30,
    i: 'pageBreak',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 60,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 90,
    i: 'pageBreak3',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 120,
    i: 'pageBreak4',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 9,
    x: 0,
    y: 0,
    minW: 2,
    minH: 9,
    i: 'offenderSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'incidentsSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'lossSummary',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 8,
    maxH: 11,
    x: 0,
    y: 11,
    i: 'crimeTypesDonut',
    moved: false,
    static: false,
  },

  {
    w: 1,
    h: 8,
    x: 1,
    y: 11,
    maxH: 11,
    i: 'crimeTypesByBusinessRadial',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'goodsTypeLossRecoveredRadial',
    moved: false,
    static: false,
  },

  {
    w: 1,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'incidentTimeOfDayDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 21,
    maxH: 11,

    i: 'incidentMonthDonut',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 34,
    minH: 4,

    i: 'incidentsDayOfWeekGraph',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 41,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
  {
    w: 2,
    minW: 2,
    h: 15,
    x: 0,
    y: 48,
    minH: 5,

    i: 'incidentsTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 56,
    i: 'targetedBusinessTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,
    y: 64,
    minH: 5,

    i: 'targetedGoodsTable',
    moved: false,
    static: false,
  },
];

export default OffenderLayout;
