import type { ExtendedLayout, MetaData } from '../../types';

export const OffenderMetaData: MetaData[] = [
  { key: 'offenderSummary', type: 'summary' },
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'crimeTypesByBusinessRadial', type: 'radial' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsHeatMap', type: 'table' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
];

const OffenderLayout: ExtendedLayout[] = [
  {
    w: 2,
    h: 9,
    x: 0,
    y: 0,
    i: 'offenderSummary',
    minW: 2,
    minH: 9,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 9,
    i: 'incidentsSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 13,
    i: 'lossSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 8,
    x: 0,
    y: 17,
    i: 'crimeTypesDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 8,
    x: 1,
    y: 17,
    i: 'crimeTypesByBusinessRadial',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 10,
    x: 0,
    y: 25,
    i: 'goodsTypeLossRecoveredRadial',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 35,
    i: 'incidentTimeOfDayDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 35,
    i: 'incidentMonthDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 45,
    i: 'incidentsDayOfWeekGraph',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 57,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 69,
    i: 'incidentsTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 84,
    i: 'targetedBusinessTable',
    minW: 2,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 99,
    i: 'targetedGoodsTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
];

export default OffenderLayout;
