image: node:20
clone:
  depth: full
pipelines:
  branches:
    dev:
      - step:
          name: Mark Development Deployment
          deployment: development
          script:
            - echo "Marking deployment to development environment"
    staging:
      - step:
          name: Mark Staging Deployment
          deployment: staging
          script:
            - echo "Marking deployment to staging environment"
    master:
      - step:
          name: Mark Production Deployment
          deployment: production
          script:
            - echo "Marking deployment to production environment"
  custom: # Pipelines that can only be triggered manually
    translations:
      - step:
          script:
            - echo "translations trigger activated!"
  pull-requests:
    feature/*:
      - step:
          caches:
            - node
          name: Checking build for merge
          size: 2x
          script:
            - export NODE_OPTIONS=--max-old-space-size=8192
            - yarn
            - yarn validate-build
            - echo "Build completed, merge allowed"
    bugfix/*:
      - step:
          size: 2x
          caches:
            - node
          name: Checking build for merge
          script:
            - export NODE_OPTIONS=--max-old-space-size=8192
            - yarn
            - yarn validate-build
            - echo "Build completed, merge allowed"
    hotfix/*:
      - step:
          size: 2x
          caches:
            - node
          name: Checking build for merge
          script:
            - export NODE_OPTIONS=--max-old-space-size=8192
            - yarn
            - yarn validate-build
            - echo "Build completed, merge allowed"
