pipelines:
  custom: # Pipelines that can only be triggered manually
    translations:
      - step:
          script:
            - echo "translations trigger activated!"
  default:
    - step:
        name: Hello world example
        script:
          - echo "Hello, World!"