mutation UpdateStockRemovalRequestRestricted($where: UniqueId!, $data: UpdateStockRemovalRequestInput!) {
    updateStockRemovalRequest(where: $where, data: $data) {
        id
        shippingAddress
        shippingAddressLine1
        shippingAddressLine2
        shippingCity
        shippingCounty
        shippingPostcode
        shippingCountry
        approvers {
            status
            id
            user {
                id
                fullName
            }
        }
    }
}
