mutation createChat($data: ChatCreateInput!) {
  createChat(data: $data) {
    id
    name
    description
    members {
      id
      newMessages
      updatedAt
      createdAt
      user {
        id
        fullName
        firstLetter
        origName
        businesses {
          fullName
          id
          name
        }
      }
      chat {
        id
        name
        firstLetter
        messages {
          id
          content
          createdAt
          from {
            id
            fullName
          }
          images {
            id
            url
            optimised
          }
          incidents {
            id
            subject
          }
          offenders {
            id
            name
          }
          vehicles {
            id
            reference
          }
          crimeGroups {
            id
            reference
          }
        }
      }
    }
  }
}
