mutation createChat($data: ChatCreateInput!) {
  createChat(data: $data) {
    id
    name
    description
    updatedAt
    createdAt
    members {
      id
      newMessages
      mentioned
      updatedAt
      createdAt
      chat {
        id
        name
        firstLetter
        totalMembers
        messages {
          id
          content
          createdAt
          from {
            id
            origName
          }
          images {
            id
          }
          incidents {
            id
          }
          offenders {
            id
          }
          vehicles {
            id
          }
          crimeGroups {
            id
          }
        }
      }
    }
  }
}
