query EditTodo($where: TodoWhereUniqueInput!) {
  todo(where: $where) {
    description
    id
    name
    dueDate
    completed
    authorised
    type
    completedDate
    business {
      id
    }
    assignedUsers {
      id
      fullName
    }

    timeTaken {
      user {
        id
      }
      timeTaken
    }
    business {
      id
    }
    questions {
      id
      question {
        id
        optionsFormatted
        optionsFormFormatted {
          label
          value
        }
        questionFormatted
        type
      }
    }
    answers {
      id
      taskQuestion {
        id
      }
      answer
    }
    groups {
      id
      name
    }
    evidence {
      id
      name
      url
      fileType
    }
    checklist {
      id
      name
      percentageScore
      percentComplete
      status
      business {
        id
        name
      }
    }
    crimeGroup {
      id
      alias
      reference
      totalIncidents
      totalOffenders
      totalRecoveredValue
      totalTheftSuccess
      totalValue
    }
    incident {
      id
      dayTime
      policeRef
      reference
      subject
      totalValue
      images {
        id
        optimised
        url
      }
    }
    offender {
      id
      name
      totalIncidents
      reference
      updatedAt
      totalValue
      images {
        id
        optimised
        url
      }
    }
    investigation {
      id
      name
      reference
      status
      createdAt
      closedAt
    }
  }
}
