query StockRemovalRequests($where: StockRemovalRequestsWhere!, $orderBy: [StockRemovalRequestsOrderBy!], $take: Int, $skip: Int) {
    stockRemovalRequests (where: $where, orderBy: $orderBy, take: $take, skip: $skip) {
        edges {
            node {
                id
                createdAt
                createdBy {
                    id
                    fullName
                }
                title
                status
                reference
                isReturn
                storeOrDC
                dateofReturn
                business {
                    id
                    name
                }
                approvers {
                    status
                    user {
                        id
                        fullName
                    }
                }
            }
        }
        totalCount
    }
}