fragment FeedUpdate on Update {
  id
  text
  icon
  type
  createdAt
  feedImage {
    ...FeedImage
  }
  linkedCrimeGroups {
    totalOffenders
    totalIncidents
    alias
    id
    reference
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    updatedAt
  }
  linkedVehicles {
    updatedAt
    totalOffenders
    registration
    reference
    model
    feedImage {
      ...FeedImage
    }
    make
    id
    colour
  }
  linkedOffenders {
    id
    updatedAt
    age
    build
    height
    dateOfBirth
    name
    race
    gender
    feedImage {
      ...FeedImage
    }
  }
  linkedIncidents {
    id
    subject
    description
    dayTime
    feedImage {
      ...FeedImage
    }
  }
  linkedArticles {
    id
    title
    updatedAt
    watermarkImage
    previewImage
    previewText
    priority
    images {
      id
      url
      optimised
      card
      position
      rotation
    }
    createdBy {
      fullName
      id
    }
  }
}
