fragment IncidentCard on Incident {
  approved
  id
  totalImages
  crimeTypes {
    id
    name
  }
  priority
  customerRef
  newIncident
  status {
    id
    name
    tooltip
  }
  assignedUsers {
    id
    fullName
  }
  images {
    low
    id
    rotation
    position
    primary
  }
  subject
  reference
  policeRef
  offenders {
    name
    id
    images(take: 1, orderBy: { createdAt: desc }) {
      id
      low
      rotation
      position
    }
  }
  dayTime
  business {
    name
  }
  location {
    full
  }
  description
  createdByUser
}
