fragment Updates on Update {
  id
  text
  type
  createdAt
  images {
    id
    url
    optimised
    position
    rotation
    primary
    policeImage
    card
  }
  linkedCrimeGroups {
    id
    reference
    alias
    totalIncidents
    totalOffenders
    totalRecoveredValue
    totalTheftSuccess
    totalValue
  }
  linkedVehicles {
    id
    reference
    colour
    model
    make
    registration
    images {
      id
      url
      optimised
      position
      rotation
      primary
      policeImage
      card
    }
  }
  linkedIncidents {
    id
    reference
    dayTime
    policeRef
    subject
    totalValue
    totalRecoveredValue
    location {
      id
      full
      geoLat
      geoLng
    }
    images {
      id
      url
      optimised
      position
      rotation
      primary
      policeImage
      card
    }
  }
  linkedOffenders {
    id
    reference
    name
    gender
    build
    height
    race
    age
    dateOfBirth
    images {
      id
      url
      optimised
      position
      rotation
      primary
      policeImage
      card
    }
  }
  createdBy {
    origName
    id
    fullName
    businesses {
      id
      name
      fullName
    }
  }
  replies {
    id
    text
    type
    createdAt
    images {
      id
      url
      optimised
      position
      rotation
      primary
      policeImage
      card
    }
    linkedCrimeGroups {
      id
      reference
      alias
      totalIncidents
      totalOffenders
      totalRecoveredValue
      totalTheftSuccess
      totalValue
    }
    linkedVehicles {
      id
      reference
      colour
      model
      make
      registration
      images {
        id
        url
        optimised
        position
        rotation
        primary
        policeImage
        card
      }
    }
    linkedIncidents {
      id
      reference
      dayTime
      policeRef
      subject
      totalValue
      totalRecoveredValue
      location {
        id
        full
        geoLat
        geoLng
      }
      images {
        id
        url
        optimised
        position
        rotation
        primary
        policeImage
        card
      }
    }
    linkedOffenders {
      id
      reference
      name
      gender
      build
      height
      race
      age
      dateOfBirth
      images {
        id
        url
        optimised
        position
        rotation
        primary
        policeImage
        card
      }
    }

    createdBy {
      origName
      id
      fullName
      businesses {
        id
        name
        fullName
      }
    }
  }
}
