fragment Updates on Update {
  id
  text
  type
  createdAt
  images {
    ...Images
  }
  linkedCrimeGroups {
    ...CrimeGroups
  }
  linkedVehicles {
    ...Vehicles
  }
  linkedIncidents {
    ...Incidents
    images {
      ...Images
    }
  }
  linkedOffenders {
    ...Offenders
  }
  createdBy {
    origName
    id
    fullName
    businesses {
      id
      name
      fullName
    }
  }
  replies {
    id
    text
    type
    createdAt
    images {
      ...Images
    }
    linkedCrimeGroups {
      ...CrimeGroups
    }
    linkedVehicles {
      ...Vehicles
    }
    linkedIncidents {
      ...Incidents
      images {
        ...Images
      }
    }
    linkedOffenders {
      ...Offenders
    }

    createdBy {
      origName
      id
      fullName
      businesses {
        id
        name
        fullName
      }
    }
  }
}
