query offenderFeedList(
  $scheme: SchemeWhereUniqueInput!
  $where: OffenderWhereInput
  $order: OffenderOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listOffenders(
    scheme: $scheme
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    offenders {
      ...OffenderCard
    }
    total
  }
}

query ListOffendersRelay(
  $after: String
  $first: Int
  $order: OffenderOrderByWithRelationInput
  $scheme: SchemeWhereUniqueInput
  $where: OffenderWhereInput
  $orderByValue: SortOrder

) {
  listOffendersRelay(
    after: $after
    first: $first
    order: $order
    scheme: $scheme
    where: $where
    orderByValue: $orderByValue

  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...OffenderCard
      }
    }
  }
}
