import type RGL from 'react-grid-layout';

import type { MetaData } from '../../../types';

export const BusinessReportMetaData: MetaData[] = [
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'involvedTagsDonut', type: 'donut' },
  { key: 'goodsTypeDonut', type: 'donut' },
  { key: 'goodsValueDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
];
const BusinessReportLayout: RGL.Layout[] = [
  {
    h: 4,
    i: 'incidentsSummary',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 0,
  },
  {
    h: 4,
    i: 'lossSummary',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 4,
  },
  {
    h: 10,
    i: 'crimeTypesDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 0,
    y: 8,
  },
  {
    h: 10,
    i: 'involvedTagsDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 1,
    y: 8,
  },
  {
    h: 10,
    i: 'goodsTypeLossRecoveredRadial',
    maxH: 11,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 18,
  },
  {
    h: 1,
    i: 'pageBreak',
    moved: false,
    static: true,
    w: 2,
    x: 0,
    y: 31,
  },
  {
    h: 10,
    i: 'incidentTimeOfDayDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 0,
    y: 32,
  },
  {
    h: 10,
    i: 'incidentMonthDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 1,
    y: 32,
  },
  {
    h: 12,
    i: 'incidentsDayOfWeekGraph',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 42,
  },
  {
    h: 1,
    i: 'pageBreak2',
    moved: false,
    static: true,
    w: 2,
    x: 0,
    y: 60,
  },
  {
    h: 16,
    i: 'incidentsTable',
    minH: 5,
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 61,
  },
  {
    h: 1,
    i: 'pageBreak3',
    moved: false,
    static: true,
    w: 2,
    x: 0,
    y: 88,
  },
  {
    h: 15,
    i: 'targetedGoodsTable',
    minH: 5,
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 89,
  },
];

export default BusinessReportLayout;
