import type RGL from 'react-grid-layout';
import type { MetaData } from '../../../types';

export const BusinessReportMetaData: MetaData[] = [
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'involvedTagsDonut', type: 'donut' },
  { key: 'goodsTypeDonut', type: 'donut' },
  { key: 'goodsValueDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
];

const BusinessReportLayout: RGL.Layout[] = [
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'incidentsSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'lossSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'goodsTypeLossRecoveredRadial',
    moved: false,
    static: false,
  },

  {
    w: 1,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'incidentTimeOfDayDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 21,
    maxH: 11,

    i: 'incidentMonthDonut',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 35,
    i: 'pageBreak',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 74,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 1,
    h: 10,
    maxH: 11,
    x: 0,
    y: 11,
    i: 'crimeTypesDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 11,
    maxH: 11,
    i: 'involvedTagsDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,
    i: 'goodsTypeDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 21,
    maxH: 11,
    i: 'goodsValueDonut',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 34,
    minH: 4,
    i: 'incidentsDayOfWeekGraph',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 16,
    x: 0,
    minW: 2,

    y: 72,
    minH: 5,

    i: 'incidentsTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 92,
    minH: 5,

    i: 'targetedGoodsTable',
    moved: false,
    static: false,
  },
];

export default BusinessReportLayout;
