query ListIncidentTags($where: IncidentTagsInput!) {
  listIncidentTags(where: $where) {
    hasChildren
    incidentForm {
      position
      type
      metadata
      conditions
    }
    label
    parentId
    parents
    policeReporting
    questions {
      answerType
      label
      questionId
      required
      tagQuestionId
      priority
      dependentOnQuestionId
      dependentOnAnswerValue
      dependentOnTagIds
      dependentOnBrandIds
      tooltip
      actions
      options {
        label
        value
      }
    }
    tier
    value
    tooltip
  }
}
