mutation updateScheme($where: UniqueId!, $data: SchemeUpdateInput!) {
  updateScheme(where: $where, data: $data) {
    id
    name
    restrictIncidentAccess
    reportOnly
    showBlankActivity
    autoApproveIncidents
    autoApproveOffenders
    defaultPublicOffenderDOB
    defaultIncidentEmail
    defaultIncidentPush
    defaultBulletinEmails
    defaultBulletinPush
    defaultSubscribedIncidentOnly
    defaultSubscribedOffenderOnly
    defaultMessagePush
    defaultOffenderEmail
    defaultOffenderPush
    autoPopulateDescription
    needJustification
    requireSiteNumberForUsers
    facialRecognition
    facialDetection
    facialRedaction
    incidentCustomQuestionRadio
    incidentTypeTooltip
    activityAssignToUser
    requireActivityAuthorised
    useBusinessGroupsOnIncident
    imagesRequiredOnOffenders
    incidentRetention
    offenderRetention
    policeReporting
    oneSelectedIncidentTypeOnly
    logo {
      id
      url
      optimised
      optimisedPersisted
    }
    darkLogo {
      id
      url
      optimised
      optimisedPersisted
    }
  }
}
