query recycledItems(
  $schemeId: String!
  $search: String
  $order: RecycledItemOrderByWithRelationInput
  $first: Int
  $after: String
  $dataType: [String!]
) {
  recycledItems(
    schemeId: $schemeId
    search: $search
    order: $order
    first: $first
    after: $after
    dataType: $dataType
  ) {
    id
    deletedAt
    deletedBy {
      id
      fullName
      organisation
    }
    expiresAt
    incident {
      id
      createdBy {
        id
        fullName
        organisation
      }
      date
      location {
        id
        full
      }
      recycled
      subject
    }
    offender {
      id
      gender
      incidents {
        id
        date
        location {
          id
          full
        }
      }
      name
      race
      recycled
    }
    scheme {
      id
    }
    systemTask
  }
}
