query Article($where: ArticleWhereUniqueInput!) {
  article(where: $where) {
    id
    watermarkImage
    groups {
      id
      name
      scheme {
        id
        name
      }
    }
    documents {
      id
      name
      url
    }
    createdBy {
      fullName
    }
    createdAt
    updatedAt
    priority
    tags {
      name
      id
    }
    schemes {
      id
      name
    }
    images {
      id
      url
      optimised
      card
      position
      rotation
    }
    image {
      id
      url
      optimised
      card
    }
    title
    rows {
      columns {
        text
        incidents {
          id
          subject
          description
          dayTime
          reference
          policeRef
          createdByUser
          crimeTypes {
            id
            name
          }
          approved
          uploaded
          location {
            id
            full
          }
          createdBy {
            id
            fullName
            businesses {
              fullName
              id
              name
            }
          }
          images {
            id
            url
            position
            rotation
            optimised
            card
            offenders {
              id
            }
          }
          groups {
            id
            name
          }
          offenders {
            id
            name
          }
        }
        offenders {
          ...OffenderCard
          lastActive {
            id
            dayTime
          }
        }
      }
    }
  }
}
