query Article($where: ArticleWhereUniqueInput!) {
  article(where: $where) {
    id
    watermarkImage
    groups {
      id
      name
      scheme {
        id
        name
      }
    }
    documents {
      id
      name
      url
    }
    createdBy {
      fullName
    }
    createdAt
    updatedAt
    priority
    completedAt
    status
    tags {
      name
      id
    }
    schemes {
      id
      name
    }
    images {
      id
      url
      optimised
      card
      position
      rotation
    }
    image {
      id
      url
      optimised
      card
    }
    title
    rows {
      columns {
        text
        incidents {
          ...IncidentCard
        }
        offenders {
          ...OffenderCard
          lastActive {
            id
            dayTime
          }
        }
      }
    }
  }
}
