query TodoList(
  $where: TodoRelayWhereInput!
  $take: Int
  $skip: Int
  $orderBy: [TodoOrderByWithRelationInput!]
  $after: String
) {
  todoRelay(
    where: $where
    take: $take
    skip: $skip
    orderBy: $orderBy
    after: $after
  ) {
    edges {
      node {
        id
        name
        authorised
        reference
        description
        dueDate
        completedDate
        completed
        createdAt
        type
        vehicleId
        business {
          name
          id
        }
        vehicle {
          id
          reference
        }
        checklist {
          id
          name
        }
        offenderId
        offender {
          id
          reference
        }
        crimeGroupId
        crimeGroup {
          id
          reference
        }
        incidentId
        incident {
          id
          reference
          crimeTypes {
            id
            name
          }
        }
        investigationId
        investigation {
          id
          reference
        }
        chatId
        assignedUsers {
          id
          fullName
        }
        groups {
          id
          name
        }
        questions {
          id
        }
      }
    }
    totalCount
    pageInfo {
      endCursor
    }
  }
}
