mutation CreateUpdateOnIncident(
  $incident: UniqueId!
  $data: CreateUpdateData!
) {
  createUpdateOnIncident(incident: $incident, data: $data) {
    id
    text
    type
    createdAt
    images {
      id
      url
      optimised
      position
      rotation
      card
    }
    linkedCrimeGroups {
      totalOffenders
      totalIncidents
      alias
      id
      reference
      totalRecoveredValue
      totalTheftSuccess
      totalValue
      updatedAt
    }
    linkedVehicles {
      images {
        id
        url
        optimised
        position
        rotation
      }
      updatedAt
      totalOffenders
      registration
      reference
      model
      make
      id
      colour
    }
    linkedIncidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
        position
        rotation
      }
    }
    linkedOffenders {
      id
      updatedAt
      age
      build
      height
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
        position
        rotation
      }
    }
    createdBy {
      origName
      id
      fullName
      businesses {
        id
        name
        fullName
      }
    }
    replies {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        card
        position
        rotation
      }
      linkedCrimeGroups {
        totalOffenders
        totalIncidents
        alias
        id
        reference
        totalRecoveredValue
        totalTheftSuccess
        totalValue
        updatedAt
      }
      linkedVehicles {
        images {
          id
          url
          optimised
          position
          rotation
        }
        updatedAt
        totalOffenders
        registration
        reference
        model
        make
        id
        colour
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        height
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      createdBy {
        origName
        id
        fullName
        businesses {
          id
          name
          fullName
        }
      }
    }
  }
}
