fragment ArticlePreview on Article {
  previewText
  watermarkImage
  previewImage
  priority
  criticalExpiry
  status
  tags {
    id
    name
  }
  images {
    id
    url
    optimised
    card
    position
    rotation
  }
  image {
    id
    url
    optimised
    card
  }
  createdBy {
    fullName
    businesses {
      id
      name
    }
    id
  }
  groups(where: $groupsWhere) {
    id
    name
  }
  title
  updatedAt
  completedAt
  id
}

query ListArticlesFeed(
  $where: ArticleWhereInput
  $scheme: SchemeWhereUniqueInput!
  $order: ArticleOrderByWithRelationInput
  $first: Int
  $after: String
  $groupsWhere: GroupWhereInput
) {
  listArticlesRelay(
    where: $where
    scheme: $scheme
    order: $order
    first: $first
    after: $after
  ) {
    edges {
      node {
        ...ArticlePreview
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
