import type RGL from 'react-grid-layout';

import type { MetaData } from '../../../types';

export const CrimeGroupMetaData: MetaData[] = [
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'offendersTable', type: 'table' },
  { key: 'crimeTypesByOffender', type: 'graph' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'offenderGoodsTypeValue', type: 'graph' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
  { key: 'incidentsHeatMap', type: 'summary' },
];
const CrimeGroupLayout: RGL.Layout[] = [
  {
    h: 4,
    i: 'incidentsSummary',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 0,
  },
  {
    h: 4,
    i: 'lossSummary',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 0,
  },
  {
    h: 8,
    i: 'crimeTypesByOffender',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 0,
    y: 11,
  },
  {
    h: 8,
    i: 'offenderGoodsTypeValue',
    maxH: 11,
    moved: false,
    static: false,
    w: 2,
    x: 1,
    y: 11,
  },
  {
    h: 10,
    i: 'goodsTypeLossRecoveredRadial',
    maxH: 11,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 21,
  },
  {
    h: 10,
    i: 'incidentTimeOfDayDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 0,
    y: 21,
  },
  {
    h: 10,
    i: 'incidentMonthDonut',
    maxH: 11,
    moved: false,
    static: false,
    w: 1,
    x: 1,
    y: 21,
  },
  {
    h: 12,
    i: 'incidentsDayOfWeekGraph',
    minH: 4,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 34,
  },
  {
    h: 12,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 41,
  },
  {
    h: 15,
    i: 'targetedBusinessTable',
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 56,
  },
  {
    h: 15,
    i: 'offendersTable',
    minH: 5,
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 64,
  },
  {
    h: 15,
    i: 'incidentsTable',
    minH: 5,
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 72,
  },
  {
    h: 15,
    i: 'targetedGoodsTable',
    minH: 5,
    minW: 2,
    moved: false,
    static: false,
    w: 2,
    x: 0,
    y: 92,
  },
];

export default CrimeGroupLayout;
