import type RGL from 'react-grid-layout';
import type { MetaData } from '../../../types';

export const CrimeGroupMetaData: MetaData[] = [
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'offendersTable', type: 'table' },
  { key: 'crimeTypesByOffender', type: 'graph' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'offenderGoodsTypeValue', type: 'graph' },
  { key: 'goodsTypeLossRecoveredRadial', type: 'radial' },
  { key: 'incidentTimeOfDayDonut', type: 'donut' },
  { key: 'incidentMonthDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
  { key: 'incidentsHeatMap', type: 'summary' },
];
const CrimeGroupLayout: RGL.Layout[] = [
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'incidentsSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'lossSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,

    y: 64,
    minH: 5,

    i: 'offendersTable',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 8,
    maxH: 11,
    x: 0,
    y: 11,
    i: 'crimeTypesByOffender',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 35,
    i: 'pageBreak',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 74,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 8,
    x: 1,
    y: 11,
    maxH: 11,
    i: 'offenderGoodsTypeValue',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'goodsTypeLossRecoveredRadial',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'incidentTimeOfDayDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 21,
    maxH: 11,

    i: 'incidentMonthDonut',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 34,
    minH: 4,

    i: 'incidentsDayOfWeekGraph',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,

    y: 72,
    minH: 5,

    i: 'incidentsTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 56,
    i: 'targetedBusinessTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 92,
    minH: 5,

    i: 'targetedGoodsTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 41,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
];

export default CrimeGroupLayout;
