mutation createMessage($data: MessageCreateWithoutActionsInput!) {
  createMessage(data: $data) {
    id
    content
    createdAt
    currentUser
    formattedDateTime
    from {
      id
      fullName
      firstLetter
    }
    sent
    showUser
    paddingTop
    type
    images {
      id
      url
      optimised
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
      }
    }
    offenders {
      id
      updatedAt
      age
      build
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
      }
    }
  }
}
