mutation createMessage($data: MessageCreateInput!) {
  createMessage(data: $data) {
    id
    content
    createdAt
    currentUser
    formattedDateTime
    from {
      id
      fullName
      firstLetter
      origFirstLetter
      origName
      businesses {
        id
        fullName
      }
    }
    sent
    showUser
    paddingTop
    type
    images {
      ...SimpleImages
    }
    crimeGroups {
      ...CrimeGroups
    }
    vehicles {
      ...Vehicles
      images {
        ...SimpleImages
      }
    }
    incidents {
      ...Incidents
      images {
        ...SimpleImages
      }
    }
    offenders {
      ...Offenders
      images {
        ...SimpleImages
      }
    }
    articles {
      ...Articles
      images {
        ...SimpleImages
      }
    }
  }
}
