mutation updateMessage(
  $where: MessageWhereUniqueInput!
  $data: MessageUpdateInput!
) {
  updateMessage(where: $where, data: $data) {
    id
    sent
    from {
      id
      fullName
      organisation
    }
    chat {
      id
      name
    }
    content
    createdAt
    images {
      id
      url
      optimised
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
      }
    }
    offenders {
      id
      age
      build
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
      }
    }
  }
}
