mutation updateMessage(
  $where: MessageWhereUniqueInput!
  $data: MessageUpdateInput!
) {
  updateMessage(where: $where, data: $data) {
    id
    sent
    from {
      id
      fullName
      origFirstLetter
      firstLetter
      businesses {
        id
        name
      }
    }
    chat {
      id
      name
    }
    content
    createdAt
    images {
      id
      url
      position
      optimised
    }
    crimeGroups {
      totalOffenders
      totalIncidents
      alias
      id
      reference
    }
    vehicles {
      registration
      reference
      model
      make
      id
      colour
      images {
        id
        optimised
        url
        position
      }
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
        position
      }
    }
    offenders {
      id
      updatedAt
      age
      build
      height
      dateOfBirth
      name
      race
      gender
      images {
        id
        url
        optimised
        position
      }
    }
  }
}
