query listOffendersAllSchemes(
  $where: OffenderWhereInput
  $order: OffenderOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listOffendersAllSchemes(
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    offenders {
      id
      reference
      reference
      age
      build
      height
      dateOfBirth
      hair
      gender
      name
      totalIncidents
      totalValue
      race
      peculiarities
      approved
      active
      lastActive {
        id
        dayTime
      }
      tags {
        id
        name
      }
      images {
        id
        optimised
        position
        rotation
        primary
        policeImage
        isFace
        optimisedPersisted
      }
    }
    total
  }
}
