query listOffendersSelect(
  $scheme: SchemeWhereUniqueInput!
  $where: OffenderWhereInput
  $order: OffenderOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listOffenders(
    scheme: $scheme
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    offenders {
      id
      name
      reference
      updatedAt
      dateOfBirth
      age
      gender
      hair
      build
      race
      peculiarities
      images {
        id
        optimised
        optimisedPersisted
      }
      incidents {
        id
        date
        location {
          id
          full
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
      }
    }
    total
  }
}
