query listOffenders(
  $scheme: SchemeWhereUniqueInput!
  $where: OffenderWhereInput
  $order: OffenderOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listOffenders(
    scheme: $scheme
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    offenders {
      id
      createdAt
      updatedAt
      totalIncidents
      reference
      age
      build
      dateOfBirth
      dateSource
      hair
      gender
      name
      race
      peculiarities
      approved
      active
      lastActive {
        id
        dayTime
      }
      tags {
        id
        name
      }
      images {
        id
        optimised
      }
      groups {
        id
        name
      }
      tags {
        id
        name
      }
      createdBy {
        id
        fullName
        organisation
      }
      incidents {
        id
        subject
        description
        dayTime
        date
        crimeTypes {
          id
          name
        }
        approved
        location {
          id
          full
        }
        createdBy {
          id
          fullName
          organisation
        }
        images {
          id
          optimised
        }
      }
    }
    total
  }
}
