query searchOffenders(
  $scheme: SchemeWhereUniqueInput!
  $where: OffenderWhereInput
  $order: OffenderOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listOffenders(
    scheme: $scheme
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    offenders {
      id
      updatedAt
      age
      build
      dateOfBirth
      dateSource
      hair
      gender
      name
      race
      peculiarities
      images {
        id
        position
        optimised
      }
      groups {
        id
        name
      }
      tags {
        id
        name
      }
      createdBy {
        id
        fullName
        businesses {
          id
          name
        }
      }
      lastActive {
        id
        dayTime
      }
    }
    total
  }
}
