query Todo($where: TodoWhereUniqueInput!) {
  todo(where: $where) {
    assignedUsers {
      id
      fullName
    }
    name
    reference
    actions {
      id
      description
      createdAt
    }
    createdAt
    dueDate
    answers {
      id
      taskQuestion {
        id
      }
      answer
    }
    evidence {
      id
      name
      url
      fileType
    }
    timeTaken {
      user {
        id
      }
      timeTaken
    }
    questions {
      id
      question {
        id
        optionsFormatted
        optionsFormFormatted {
          label
          value
        }
        questionFormatted
        type
      }
    }
    business {
      id
      name
      locations {
        geoLat
        geoLng
      }
    }
    description
    id
  }
}
