import React from 'react';
import { useParams } from 'react-router-dom';
import View from './ViewIncident.view';
import useViewIncident from './useViewIncident';
import useApproveIncident from './useApproveIncident';

const ViewIncident = (): JSX.Element => {
  const incidentId = useParams().id || '';
  const {
    data,
    loading,
    saving,
    openLightbox,
    deleteRights,
    editRights,
    linkOffender,
    toggleLinkOffender,
    updateOffendersList,
    loadMore,
    scrolledToTop,
    userId,
    replyTo,
    setReplyTo,
    confirmUpdateImages,
    addImages,
    addUpdateImages,
    closeAddImages,
    toggleSubscribe,
    selectedImages,
    toggleSelectImages,
    confirmDeleteUpdate,
    editUpdate,
    editUpdateInput,
    handleEditUpdate,
    setEditUpdate,
    setEditUpdateInput,
    lightboxElements,
    lightBoxOpen,
    optionRowShow,
    setOptionRowShow,
    onDelete,
    editIncident,
    toggleEditIncident,
    editImages,
    toggleEditImages,
    editImageData,
    setEditImageData,
    onDeleteImage,
    onEditImage,
    addOffender,
    addExistingOffender,
    editOffenderData,
    setEditOffenderData,
    onDeleteOffender,
    toggleAddOffender,
    toggleAddExistingOffender,
    addVehicle,
    addExistingVehicle,
    editVehicleData,
    setEditVehicleData,
    onDeleteVehicle,
    toggleAddVehicle,
    toggleAddExistingVehicle,
    addGoods,
    editGoodsData,
    setEditGoodsData,
    onDeleteGoods,
    toggleAddGoods,
    onEditVehicle,
    onAddVehicle,
    onAddExistingVehicle,
    onEditGoods,
    onAddGoods,
    onEditOffender,
    onAddOffender,
    onAddExistingOffender,
    onUpdateImages,
    goodsMode,
    addTodo,
    toggleAddTodo,
    updateTodoList,
    toggleAddDocument,
    addDocument,
    updateDocumentList,
    updateDeleteDocument,
    hideIncident,
    userRole,
    translateText,
    isTranslated,
    languageCount,
    templatesData,
    templatesLoading,
    setViewTodoVisible,
    setCompleteTodoVisible,
    completeTodoVisible,
    viewTodoVisible,
    updateTodo,
    addInvestigation,
    toggleAddInvestigation,
    updateInvestigationList,
    editAddress,
    toggleEditAddress,
    onEditAddress,
  } = useViewIncident(incidentId);
  const { onApprove, onReject, approving } = useApproveIncident({ incidentId });

  return (
    <View
      languageCount={languageCount}
      isTranslated={isTranslated}
      translateText={translateText}
      userRole={userRole}
      data={data}
      loading={loading}
      saving={saving}
      openLightbox={openLightbox}
      incidentId={incidentId}
      deleteRights={deleteRights}
      editRights={editRights}
      linkOffender={linkOffender}
      toggleLinkOffender={toggleLinkOffender}
      updateOffendersList={updateOffendersList}
      loadMore={loadMore}
      scrolledToTop={scrolledToTop}
      userId={userId}
      replyTo={replyTo}
      setReplyTo={setReplyTo}
      confirmUpdateImages={confirmUpdateImages}
      addImages={addImages}
      addUpdateImages={addUpdateImages}
      closeAddImages={closeAddImages}
      toggleSubscribe={toggleSubscribe}
      selectedImages={selectedImages}
      toggleSelectImages={toggleSelectImages}
      confirmDeleteUpdate={confirmDeleteUpdate}
      editUpdate={editUpdate}
      editUpdateInput={editUpdateInput}
      handleEditUpdate={handleEditUpdate}
      setEditUpdate={setEditUpdate}
      setEditUpdateInput={setEditUpdateInput}
      onDelete={onDelete}
      lightboxElements={lightboxElements}
      lightBoxOpen={lightBoxOpen}
      optionRowShow={optionRowShow}
      setOptionRowShow={setOptionRowShow}
      onApprove={onApprove}
      onReject={onReject}
      approving={approving}
      editIncident={editIncident}
      toggleEditIncident={toggleEditIncident}
      editImages={editImages}
      toggleEditImages={toggleEditImages}
      editImageData={editImageData}
      setEditImageData={setEditImageData}
      onDeleteImage={onDeleteImage}
      onEditImage={onEditImage}
      addOffender={addOffender}
      addExistingOffender={addExistingOffender}
      editOffenderData={editOffenderData}
      setEditOffenderData={setEditOffenderData}
      onDeleteOffender={onDeleteOffender}
      toggleAddOffender={toggleAddOffender}
      toggleAddExistingOffender={toggleAddExistingOffender}
      addVehicle={addVehicle}
      addExistingVehicle={addExistingVehicle}
      editVehicleData={editVehicleData}
      setEditVehicleData={setEditVehicleData}
      onDeleteVehicle={onDeleteVehicle}
      toggleAddVehicle={toggleAddVehicle}
      toggleAddExistingVehicle={toggleAddExistingVehicle}
      addGoods={addGoods}
      editGoodsData={editGoodsData}
      setEditGoodsData={setEditGoodsData}
      onDeleteGoods={onDeleteGoods}
      toggleAddGoods={toggleAddGoods}
      onEditVehicle={onEditVehicle}
      onAddVehicle={onAddVehicle}
      onAddExistingVehicle={onAddExistingVehicle}
      onEditGoods={onEditGoods}
      onAddGoods={onAddGoods}
      onEditOffender={onEditOffender}
      onAddOffender={onAddOffender}
      onAddExistingOffender={onAddExistingOffender}
      onUpdateImages={onUpdateImages}
      goodsMode={goodsMode}
      addTodo={addTodo}
      toggleAddTodo={toggleAddTodo}
      updateTodoList={updateTodoList}
      toggleAddDocument={toggleAddDocument}
      addDocument={addDocument}
      updateDocumentList={updateDocumentList}
      updateDeleteDocument={updateDeleteDocument}
      hideIncident={hideIncident}
      templatesData={templatesData}
      templatesLoading={templatesLoading}
      completeTodoVisible={completeTodoVisible}
      setCompleteTodoVisible={setCompleteTodoVisible}
      setViewTodoVisible={setViewTodoVisible}
      viewTodoVisible={viewTodoVisible}
      updateTodo={updateTodo}
      addInvestigation={addInvestigation}
      toggleAddInvestigation={toggleAddInvestigation}
      updateInvestigationList={updateInvestigationList}
      editAddress={editAddress}
      toggleEditAddress={toggleEditAddress}
      onEditAddress={onEditAddress}
    />
  );
};

export default ViewIncident;
