subscription MessagesSubscription($chat: ID!, $user: ID!) {
  chatMessages(chatId: $chat, userId: $user) {
    id
    content
    createdAt
    currentUser
    formattedDateTime
    from {
      id
      fullName
      firstLetter
    }
    sent
    showUser
    paddingTop
    type
    images {
      ...SimpleImages
    }
    crimeGroups {
      ...CrimeGroups
    }
    vehicles {
      ...Vehicles
      images {
        ...SimpleImages
      }
    }
    incidents {
      ...Incidents
      images {
        ...SimpleImages
      }
    }
    offenders {
      ...Offenders
      images {
        ...SimpleImages
        isFace
      }
    }
    articles {
      ...Articles
      images {
        ...SimpleImages
      }
    }
  }
}
