subscription MessagesSubscription($chat: ID!) {
  messages(chatId: $chat) {
    id
    sent
    from {
      id
      fullName
      organisation
    }
    chat {
      id
      name
    }
    content
    createdAt
    images {
      id
      url
      optimised
    }
    incidents {
      id
      subject
      description
      dayTime
      images {
        id
        url
        optimised
      }
    }
    offenders {
      id
      updatedAt
      name
      images {
        id
        url
        optimised
      }
    }
  }
}
