query ListCrimeGroups(
  $take: Int
  $skip: Int
  $where: CrimeGroupWhereInput
  $order: CrimeGroupOrderByWithRelationInput
) {
  listCrimeGroups(take: $take, skip: $skip, where: $where, order: $order) {
    crimeGroups {
      id
      reference
      totalIncidents
      totalOffenders
      totalRecoveredValue
      totalTheftSuccess
      totalValue
      alias
      updatedAt
      offenders(take: 3) {
        id
        name
        images(take: 1) {
          id
          optimised
        }
      }
    }
    total
  }
}
