query SuggestedCrimeGroupMembers(
  $where: CrimeGroupWhereUniqueInput!
  $associatedCrimeGroup: UniqueId
) {
  crimeGroup(where: $where) {
    id
    suggestedMembers {
      id
      name
      alias
      reference
      dateOfBirth
      age
      gender
      build
      height
      race
      hair
      peculiarities
      images {
        id
        optimised
        position
        rotation
      }
      totalAssociatedIncidents(associatedCrimeGroup: $associatedCrimeGroup)
      associatedIncidents(associatedCrimeGroup: $associatedCrimeGroup) {
        id
        crimeTypes {
          id
          name
        }
      }
    }
  }
}
