query CrimeGroup($where: CrimeGroupWhereUniqueInput!) {
  crimeGroup(where: $where) {
    id
    reference
    totalIncidents
    totalOffenders
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    subscribed
    alias
    groups {
      id
    }
    offenders {
      id
      name
      reference
      lastActive {
        id
        dayTime
      }
      hair
      peculiarities
      race
      dateOfBirth
      dateSource
      build
      height
      age
      gender
      images {
        id
        optimised
        position
        rotation
      }
      totalTheftSuccess
      totalRecoveredValue
      totalIncidents
      totalValue
    }
    vehicles {
      id
      reference
      make
      model
      updatedAt
      colour
      registration
      totalOffenders
      totalIncidents
      totalCrimeGroups
    }
    incidents {
      id
      reference
      dayTime
      date
      crimeTypes {
        id
        name
      }
      createdBy {
        id
        businesses {
          id
          name
          fullName
        }
      }
      location {
        full
        id
        geoLat
        geoLng
      }
    }
    updates(orderBy: { createdAt: desc }) {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        position
        rotation
        card
      }
      linkedCrimeGroups {
        totalOffenders
        totalIncidents
        alias
        id
        reference
        totalRecoveredValue
        totalTheftSuccess
        totalValue
        updatedAt
      }
      linkedVehicles {
        updatedAt
        totalOffenders
        registration
        reference
        model
        make
        id
        colour
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        height
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      createdBy {
        origName
        id
        fullName
        businesses {
          id
          name
          fullName
        }
      }
      replies {
        id
        text
        type
        createdAt
        images {
          id
          url
          optimised
          card
          position
          rotation
        }
        linkedCrimeGroups {
          totalOffenders
          totalIncidents
          alias
          id
          reference
          totalRecoveredValue
          totalTheftSuccess
          totalValue
          updatedAt
        }
        linkedVehicles {
          updatedAt
          totalOffenders
          registration
          reference
          model
          make
          id
          colour
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        linkedIncidents {
          id
          subject
          description
          dayTime
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        linkedOffenders {
          id
          updatedAt
          age
          build
          height
          dateOfBirth
          name
          race
          gender
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        createdBy {
          origName
          id
          fullName
          businesses {
            id
            name
            fullName
          }
        }
      }
    }
  }
}
