query CrimeGroup($where: CrimeGroupWhereUniqueInput!) {
  crimeGroup(where: $where) {
    id
    reference
    totalIncidents
    totalOffenders
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    subscribed
    alias
    groups {
      id
    }

    incidents {
      ...Incidents
    }
    vehicles {
      ...Vehicles
    }
    offenders {
      ...Offenders
      images {
        ...Images
      }
    }
    evidence {
      ...Documents
    }
    investigations {
      ...Investigations
    }
    updates(orderBy: { createdAt: desc }) {
      ...Updates
    }
  }
}
