query CrimeGroup($where: CrimeGroupWhereUniqueInput!) {
  crimeGroup(where: $where) {
    id
    reference
    totalIncidents
    totalOffenders
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    subscribed
    alias
    groups {
      id
    }
    activities {
      id
      description
      dueDate
      completed
      completedDate
      reference
      createdAt
      assignedUsers {
        id
        fullName
      }
      completedBy {
        id
        fullName
      }
      name
    }
    incidents {
      ...IncidentsDetailed
    }
    vehicles {
      ...Vehicles
      images {
        ...Images
      }
    }
    offenders {
      ...Offenders
      alias
      totalIncidents
      totalValue
      latestIncident {
        id
        date
      }
      knownFor
      targetedBusinesses {
        id
        name
      }
      targetedGoods
      images {
        ...Images
      }
    }
    evidence {
      ...Documents
    }
    investigations {
      ...Investigations
    }
    updates(orderBy: { createdAt: desc }) {
      ...Updates
    }
  }
}
