query stockRemovalRequest($where: UniqueId!) {
    stockRemovalRequest (where: $where) {
        id
        createdAt
        title
        description
        status
        reference
        costCentreCode
        fascia
        personalityInfluences
        reason
        reasonForNonReturn
        rechargeBrand
        rechargeReference
        returnDate
        shippingAddress
        smqAccountNumber
        socialHandles
        storeOrDC
        willStockBeReturned
        tmid
        tracking
        createdBy {
            id
            fullName
        }
        items {
            id
            name
            brand
            sku
            barcode
            requestedQuantity
            pickedQuantity
            value
        }
        business {
            id
            name
        }
        approvers {
            status
            id
            user {
                id
                fullName
            }
        }
    }
}