query ListVehicles(
    $take: Int
    $skip: Int
    $where: VehicleWhereInput
    $order: VehicleOrderByWithRelationInput
    $policeAreas: [PoliceForce!]
) {
    listVehicles(take: $take, skip: $skip, where: $where, order: $order, policeAreas: $policeAreas) {
        vehicles {
            id
            make
            model
            registration
            totalCrimeGroups
            totalOffenders
            totalIncidents
            reference
            totalImages
            images {
                id
                optimised
                url
                position
                rotation
            }
            incidents {
                id
                subject
            }
            offenders {
                id
                name
            }
            updatedAt
            colour
            crimeGroup {
                id
                reference
            }
        }
        total
    }
}
