query ListVehicles(
  $take: Int
  $skip: Int
  $where: VehicleWhereInput
  $order: VehicleOrderByWithRelationInput
) {
  listVehicles(take: $take, skip: $skip, where: $where, order: $order) {
    vehicles {
      id
      make
      model
      registration
      totalCrimeGroups
      totalOffenders
      totalIncidents
      reference
      images {
        id
        optimised
        url
      }
      incidents {
        id
        subject
      }
      offenders {
        id
        name
      }
      updatedAt
      colour
      crimeGroup {
        id
        reference
      }
    }
    total
  }
}
