query Vehicle($where: VehicleWhereUniqueInput!) {
  vehicle(where: $where) {
    id
    make
    model
    registration
    totalOffenders
    totalIncidents
    totalCrimeGroups
    reference
    subscribed
    customGalleries {
      id
      name
    }

    groups {
      id
      name
    }

    updatedAt
    colour
    crimeGroups {
      ...CrimeGroups
    }
    offenders {
      ...Offenders
    }
    todos {
      ...Todos
    }
    incidents {
      ...Incidents
    }
    evidence {
      ...Documents
    }
    investigations {
      ...Investigations
    }
    updates(orderBy: { createdAt: desc }) {
      ...Updates
    }
  }
}
