query ListSchemeUsers(
  $where: UserWhereInput
  $orderBy: [UserOrderByWithRelationInput!]
  $after: UserWhereUniqueInput
  $groupWhere: GroupWhereInput
  $schemesWhere: UserSchemeWhereInput
) {
  users(where: $where, orderBy: $orderBy, after: $after) {
    id
    fullName
    firstLetter
    origName
    origFirstLetter
    email
    publicName
    businesses {
      id
      name
      fullName
    }
    status
    groups(where: $groupWhere) {
      id
      name
    }
    schemes(where: $schemesWhere) {
      id
      role
      scheme {
        id
      }
    }
    approverGroups(where: $groupWhere) {
      id
      name
    }
  }
}
