query userChats(
  $where: UserWhereUniqueInput!
  $orderBy: [UserChatOrderByWithRelationInput!]
  $scheme: String!
) {
  user(where: $where) {
    id
    chats(
      where: { chat: { scheme: { id: { equals: $scheme } } } }
      orderBy: $orderBy
    ) {
      id
      newMessages
      updatedAt
      user {
        id
        fullName
        firstLetter
      }
      chat {
        id
        name
        firstLetter
        totalMembers
        messages {
          id
          content
          createdAt
          from {
            id
            fullName
          }
        }
      }
    }
  }
}
