query userChats(
  $where: UserWhereUniqueInput!
  $orderBy: [UserChatOrderByWithRelationInput!]
  $scheme: String!
) {
  user(where: $where) {
    id
    totalChats
    chats(
      where: { chat: { scheme: { id: { equals: $scheme } } } }
      orderBy: $orderBy
    ) {
      id
      newMessages
      mentioned
      updatedAt
      createdAt
      chat {
        id
        name
        firstLetter
        totalMembers
        messages(first: 1, orderBy: [{ createdAt: desc }]) {
          id
          content
          createdAt
          from {
            id
            origName
          }
          images {
            id
          }
          incidents {
            id
          }
          offenders {
            id
          }
          vehicles {
            id
          }
          crimeGroups {
            id
          }
        }
      }
    }
  }
}
