mutation createIncident($data: CreateIncidentData!) {
  createIncident(data: $data) {
    id
    subject
    description
    dayTime
    date
    time
    value
    recoveredValue
    policeReported
    policeRef
    policeInvolved
    crimeTypes {
      id
      name
    }
    approved
    location {
      id
      full
    }
    createdBy {
      id
      fullName
      businesses {
        fullName
        id
        name
      }
    }
    images {
      id
      optimised
      url
      position
    }
    groups {
      id
      name
    }
    offenders {
      id
      createdAt
      updatedAt
      age
      build
      height
      dateOfBirth
      dateSource
      gender
      hair
      name
      peculiarities
      race
      approved
      uploaded
      active
      images {
        id
        url
        optimised
        card
        position
      }
      tags {
        id
        name
      }
    }
  }
}
