query listIncidents(
  $scheme: SchemeWhereUniqueInput!
  $where: IncidentWhereInput
  $order: IncidentOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listIncidents(
    scheme: $scheme
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    incidents {
      id
      subject
      totalImages
      description
      dayTime
      reference
      policeRef
      crimeTypes {
        id
        name
      }
      approved
      business {
        id
        name
      }
      location {
        id
        full
      }
      createdBy {
        id
        fullName
        businesses {
          id
          name
        }
      }
      images {
        id
        position
        rotation
        optimised
        url
      }
      groups {
        id
        name
      }
      offenders {
        id
        name
      }
    }
    total
  }
}
