query listIncidentsAllSchemes(
  $where: IncidentWhereInput
  $order: IncidentOrderByWithRelationInput
  $take: Int
  $skip: Int
) {
  listIncidentsAllSchemes(
    where: $where
    order: $order
    take: $take
    skip: $skip
  ) {
    incidents {
      id
      subject
      description
      dayTime
      reference
      policeRef
      date
      approved
      business {
        id
        name
      }
      location {
        id
        full
      }
      offenders {
        id
        name
      }
    }
    total
  }
}
