query unrestrictedIncidentsRelay(
  $take: Int
  $skip: Int
  $orderBy: IncidentOrderByWithRelationInput
  $where: UnrestrictedIncidentRelayInput!
) {
  unrestrictedIncidentsRelay(
    take: $take
    skip: $skip
    orderBy: $orderBy
    where: $where
  ) {
    edges {
      node {
        id
        subject
        dayTime
        reference
        policeRef
        business {
          id
          name
        }
        location {
          id
          full
        }
        incidentItems {
          value
          recoveredValue
          quantity
          recoveredQuantity
        }
        offenders {
          id
          name
          images(take: 1) {
            id
            optimised
          }
        }
      }
    }
    totalCount
  }
}
