query ViewIncident($where: IncidentWhereUniqueInput!) {
  incident(where: $where) {
    id
    subject
    description
    dayTime
    date
    time
    value
    recoveredValue
    subscribed
    crimeTypes {
      id
      name
    }
    approved
    location {
      id
      building
      street
      townCity
      county
      postcode
      full
    }
    createdBy {
      id
      fullName
      organisation
    }
    images {
      id
      optimised
      url
    }
    groups {
      id
      name
    }
    offenders {
      id
      createdAt
      updatedAt
      age
      build
      dateOfBirth
      dateSource
      gender
      hair
      name
      peculiarities
      race
      approved
      uploaded
      active
      images {
        id
        url
        optimised
        card
      }
      tags {
        id
        name
      }
    }
    updates(orderBy: { createdAt: desc }) {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        card
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
        }
      }
      createdBy {
        id
        fullName
        organisation
      }
      replies {
        id
        text
        type
        createdAt
        images {
          id
          url
          optimised
          card
        }
        linkedIncidents {
          id
          subject
          description
          dayTime
          images {
            id
            url
            optimised
          }
        }
        linkedOffenders {
          id
          updatedAt
          age
          build
          dateOfBirth
          name
          race
          gender
          images {
            id
            url
            optimised
          }
        }
        createdBy {
          id
          fullName
          organisation
        }
      }
    }
  }
}
