query ViewIncident($where: IncidentWhereUniqueInput!) {
  incident(where: $where) {
    id
    subject
    description
    dayTime
    date
    time
    reference
    policeReported
    policeRef
    policeInvolved
    subscribed
    totalValue
    totalRecoveredValue
    crimeTypes {
      id
      name
      crimeType
    }
    incidentItems {
      id
      name
      value
      recoveredValue
      goodsType {
        id
      }
    }
    approved
    business {
      id
      name
    }
    createdBy {
      id
      fullName
      businesses {
        id
        name
      }
    }
    images {
      id
      optimised
      url
    }
    groups {
      id
      name
    }
    crimeGroups {
      id
      reference
      alias
      totalIncidents
      totalOffenders
      totalRecoveredValue
      totalTheftSuccess
      totalValue
    }
    vehicles {
      id
      colour
      model
      make
      registration
      totalCrimeGroups
      totalIncidents
      totalOffenders
      updatedAt
    }
    offenders {
      id
      createdAt
      updatedAt
      age
      build
      dateOfBirth
      dateSource
      gender
      hair
      name
      peculiarities
      race
      approved
      uploaded
      active
      images {
        id
        url
        optimised
        card
      }
      tags {
        id
        name
      }
    }
    updates(orderBy: { createdAt: desc }) {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        card
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
        }
      }
      createdBy {
        id
        fullName
        businesses {
          id
          name
        }
      }
      replies {
        id
        text
        type
        createdAt
        images {
          id
          url
          optimised
          card
        }
        linkedIncidents {
          id
          subject
          description
          dayTime
          images {
            id
            url
            optimised
          }
        }
        linkedOffenders {
          id
          updatedAt
          age
          build
          dateOfBirth
          name
          race
          gender
          images {
            id
            url
            optimised
          }
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
      }
    }
  }
}
