query ViewIncident($where: IncidentWhereUniqueInput!) {
  incident(where: $where) {
    id
    subject
    totalImages
    description
    dayTime
    date
    time
    reference
    ref
    policeReported
    policeRef
    policeNo
    policeInvolved
    subscribed
    totalValue
    totalRecoveredValue
    answers {
      id
      answer
      tagQuestion {
        id
        priority
        question {
          id
          question
        }
      }
      type
    }
    evidence {
      id
      name
      url
      fileType
    }
    scheme {
      mg11Available
    }
    crimeTypes {
      id
      name
      crimeType
    }
    involvedTags {
      id
      name
    }
    impactTags {
      id
      name
    }

    incidentItems {
      id
      name
      value
      recoveredValue
      sku
      quantity
      recoveredQuantity
      goodsType {
        id
      }
    }
    approved
    business {
      id
      name
    }
    createdBy {
      id
      fullName
      businesses {
        id
        name
      }
    }
    images {
      id
      url
      optimised
      position
      rotation
      primary
      policeImage
    }
    groups {
      id
      name
    }
    crimeGroups {
      id
      reference
      alias
      totalIncidents
      totalOffenders
      totalRecoveredValue
      totalTheftSuccess
      totalValue
    }
    vehicles {
      id
      reference
      colour
      model
      make
      registration
      images {
        id
        url
        position
        rotation
        optimised
        primary
        policeImage
      }
    }
    todos {
      id
      name
      description
      dueDate
      completed
      assignedUsers {
        id
        fullName
      }
    }

    offenders {
      id
      reference
      age
      build
      height
      dateOfBirth
      dateSource
      gender
      hair
      name
      peculiarities
      race
      approved
      uploaded
      active
      images {
        id
        url
        optimised
        position
        rotation
        primary
        policeImage
        card
      }
    }
    updates(orderBy: { createdAt: asc }) {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        position
        rotation
        card
      }
      linkedCrimeGroups {
        totalOffenders
        totalIncidents
        alias
        id
        reference
        totalRecoveredValue
        totalTheftSuccess
        totalValue
        updatedAt
      }
      linkedVehicles {
        images {
          id
          url
          position
          rotation
          optimised
        }
        updatedAt
        totalOffenders
        registration
        reference
        model
        make
        id
        colour
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        height
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
          position
          rotation
        }
      }
      createdBy {
        origName
        id
        fullName
        businesses {
          id
          name
          fullName
        }
      }
      replies {
        id
        text
        type
        createdAt
        images {
          id
          url
          optimised
          position
          rotation
          card
        }
        linkedCrimeGroups {
          totalOffenders
          totalIncidents
          alias
          id
          reference
          totalRecoveredValue
          totalTheftSuccess
          totalValue
          updatedAt
        }
        linkedVehicles {
          images {
            id
            url
            optimised
            position
            rotation
          }
          updatedAt
          totalOffenders
          registration
          reference
          model
          make
          id
          colour
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        linkedIncidents {
          id
          subject
          description
          dayTime
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        linkedOffenders {
          id
          updatedAt
          age
          build
          height
          dateOfBirth
          name
          race
          gender
          images {
            id
            url
            optimised
            position
            rotation
          }
        }
        createdBy {
          origName
          id
          fullName
          businesses {
            id
            name
            fullName
          }
        }
      }
    }
    location {
      geoLat
      geoLng
      id
    }
  }
}
