mutation CreateTodo($data: TodoCreateInput!) {
  createTodo(data: $data) {
    id
    name
    description
    dueDate
    completedDate
    completed
    createdAt
    type
    vehicleId
    vehicle {
      id
      reference
    }
    offenderId
    offender {
      id
      reference
    }
    crimeGroupId
    crimeGroup {
      id
      reference
    }
    incidentId
    incident {
      id
      reference
    }
    investigationId
    investigation {
      id
      reference
    }
    chatId
    assignedUsers {
      id
      fullName
    }
    groups {
      id
      name
    }
  }
}
