mutation UpdateInvestigation(
  $where: UniqueId!
  $data: UpdateInvestigationInput!
) {
  updateInvestigation(where: $where, data: $data) {
    id
    description
    name
    groups {
      id
      name
    }
    createdBy {
      id
      fullName
    }
    vehicles {
      ...Vehicles
      images {
        ...Images
      }
    }
    offenders {
      ...Offenders
      images {
        id
        optimised
        optimisedPersisted
        position
        rotation
        isFace
      }
    }
    incidents {
      id
      policeRef
      dayTime
      createdBy {
        organisation
      }
      reference
      subject
      date
      location {
        id
      }
      value
      recoveredValue
      vehicles {
        ...Vehicles
        images {
          id
          optimised
          position
          rotation
        }
      }
      offenders {
        ...Offenders
        images {
          id
          optimised
          position
          rotation
        }
      }
    }
    crimeGroups {
      id
      alias
      reference
      vehicles {
        id
        reference
        registration
        make
        model
        images {
          id
          optimised
          position
          rotation
        }
        colour
      }
      offenders {
        id
        name
        alias
        reference
        dateOfBirth
        age
        gender
        build
        height
        race
        hair
        peculiarities
        images {
          id
          optimised
          position
          rotation
        }
      }
    }
    flows {
      name

      description
      edges {
        id
        type
        markerEnd
        source
        sourceHandle
        target
        targetHandle
      }
      nodes {
        id
        type
        data
        height
        width
        position {
          x
          y
        }
        positionAbsolute {
          x
          y
        }
      }
    }
  }
}
