query Business($where: BusinessWhereUniqueInput!) {
  business(where: $where) {
    id
    name
    fullName
    publicName
    demId
    incidents {
      id
      reference
      dayTime
      date
      crimeTypes {
        id
        name
      }
      createdBy {
        id
        businesses {
          id
          name
          fullName
        }
      }
      location {
        id
        full
        geoLat
        geoLng
      }
    }
    todos {
      id
      name
      description
      dueDate
      completed
      assignedUsers {
        id
        fullName
      }
    }
    parent {
      id
      name
      fullName
    }
    locations {
      id
      full
      geoLat
      geoLng
    }
  }
}
