query Business(
  $where: BusinessWhereUniqueInput!
  $incidentsWhere: IncidentWhereInput
) {
  business(where: $where) {
    id
    name
    fullName
    publicName
    demId
    siteNumber
    groups {
      id
      name
    }
    tags {
      id
      name
    }
    incidents(where: $incidentsWhere) {
      id
      reference
      dayTime
      date
      crimeTypes {
        id
        name
      }
      createdBy {
        id
        businesses {
          id
          name
          fullName
        }
      }
      location {
        ...Locations
      }
    }
    todos {
      ...Todos
    }
    parent {
      id
      name
      fullName
    }
    locations {
      id
      full
      geoLat
      geoLng
    }
  }
}
