query Business($where: BusinessWhereUniqueInput!) {
  business(where: $where) {
    id
    name
    fullName
    publicName
    demId
    groups {
      id
      name
    }
    tags {
      id
      name
    }
    incidents {
      id
      reference
      dayTime
      date
      crimeTypes {
        id
        name
      }
      createdBy {
        id
        businesses {
          id
          name
          fullName
        }
      }
      location {
        ...Locations
      }
    }
    todos {
      ...Todos
    }
    parent {
      id
      name
      fullName
    }
    locations {
      id
      full
      geoLat
      geoLng
    }
  }
}
