import React from 'react';

import { useParams } from 'react-router-dom';
import View from './ViewInvestigation.view';
import useViewCustomer from './useViewInvestigation';

const ViewCustomer: React.FC = () => {
  const { id } = useParams();

  const {
    data,
    offenderIds,
    vehicleIds,
    incidentIds,
    crimeGroupIds,
    toggleAddDocument,
    addDocument,
    toggleAddDemDocument,
    addDemDocument,
    demId,
    toggleSubscribe,
    takeAllSchemes,
    addTodo,
    toggleAddTodo,
    templatesData,
    templatesLoading,
    setViewTodoVisible,
    setCompleteTodoVisible,
    completeTodoVisible,
    viewTodoVisible,
    updateTodo,
    updateTodoList,
    addOffender,
    addExistingOffender,
    toggleAddOffender,
    toggleAddExistingOffender,
    editOffenderData,
    setEditOffenderData,
    onDeleteOffender,
    addVehicle,
    addExistingVehicle,
    toggleAddVehicle,
    toggleAddExistingVehicle,
    editVehicleData,
    setEditVehicleData,
    onDeleteVehicle,
    addCrimeGroup,
    addExistingCrimeGroup,
    toggleAddCrimeGroup,
    toggleAddExistingCrimeGroup,
    editCrimeGroupData,
    setEditCrimeGroupData,
    addExistingIncident,
    toggleAddExistingIncident,
    onAddExistingOffender,
    onAddExistingVehicle,
    onAddExistingCrimeGroup,
    onAddExistingIncident,
    onAddOffender,
    onEditOffender,
    onAddVehicle,
    onEditVehicle,
    onAddCrimeGroup,
    onEditCrimeGroup,
    onDeleteCrimeGroup,
    onDeleteIncident,
    saving,
    loading,
    onDeleteInvestigation,
    suggestedOffenders,
    suggestedVehicles,
    toggleCloseSuggestedOffenders,
    toggleCloseSuggestedVehicles,
    onAddExistingOffenders,
    onAddExistingVehicles,
    showSuggestedVehicles,
    showSuggestedOffenders,
    toggleShowSuggestedVehicles,
    toggleShowSuggestedOffenders,
    editInvestigation,
    toggleEditInvestigation,
  } = useViewCustomer(id || '');

  return (
    <View
      loading={loading}
      demId={demId}
      toggleAddDocument={toggleAddDocument}
      addDocument={addDocument}
      toggleAddDemDocument={toggleAddDemDocument}
      addDemDocument={addDemDocument}
      data={data}
      vehicleIds={vehicleIds}
      crimeGroupIds={crimeGroupIds}
      offenderIds={offenderIds}
      incidentIds={incidentIds}
      toggleSubscribe={toggleSubscribe}
      takeAllSchemes={takeAllSchemes}
      addTodo={addTodo}
      toggleAddTodo={toggleAddTodo}
      templatesData={templatesData}
      templatesLoading={templatesLoading}
      setViewTodoVisible={setViewTodoVisible}
      setCompleteTodoVisible={setCompleteTodoVisible}
      completeTodoVisible={completeTodoVisible}
      viewTodoVisible={viewTodoVisible}
      updateTodo={updateTodo}
      updateTodoList={updateTodoList}
      addOffender={addOffender}
      addExistingOffender={addExistingOffender}
      toggleAddOffender={toggleAddOffender}
      toggleAddExistingOffender={toggleAddExistingOffender}
      editOffenderData={editOffenderData}
      setEditOffenderData={setEditOffenderData}
      onDeleteOffender={onDeleteOffender}
      addVehicle={addVehicle}
      addExistingVehicle={addExistingVehicle}
      toggleAddVehicle={toggleAddVehicle}
      toggleAddExistingVehicle={toggleAddExistingVehicle}
      editVehicleData={editVehicleData}
      setEditVehicleData={setEditVehicleData}
      onDeleteVehicle={onDeleteVehicle}
      addCrimeGroup={addCrimeGroup}
      addExistingCrimeGroup={addExistingCrimeGroup}
      toggleAddCrimeGroup={toggleAddCrimeGroup}
      toggleAddExistingCrimeGroup={toggleAddExistingCrimeGroup}
      editCrimeGroupData={editCrimeGroupData}
      setEditCrimeGroupData={setEditCrimeGroupData}
      addExistingIncident={addExistingIncident}
      toggleAddExistingIncident={toggleAddExistingIncident}
      onAddExistingOffender={onAddExistingOffender}
      onAddExistingVehicle={onAddExistingVehicle}
      onAddExistingCrimeGroup={onAddExistingCrimeGroup}
      onAddExistingIncident={onAddExistingIncident}
      onAddOffender={onAddOffender}
      onEditOffender={onEditOffender}
      onAddVehicle={onAddVehicle}
      onEditVehicle={onEditVehicle}
      onAddCrimeGroup={onAddCrimeGroup}
      onEditCrimeGroup={onEditCrimeGroup}
      onDeleteCrimeGroup={onDeleteCrimeGroup}
      onDeleteIncident={onDeleteIncident}
      saving={saving}
      onDeleteInvestigation={onDeleteInvestigation}
      suggestedOffenders={suggestedOffenders}
      suggestedVehicles={suggestedVehicles}
      toggleCloseSuggestedOffenders={toggleCloseSuggestedOffenders}
      toggleCloseSuggestedVehicles={toggleCloseSuggestedVehicles}
      onAddExistingOffenders={onAddExistingOffenders}
      onAddExistingVehicles={onAddExistingVehicles}
      showSuggestedVehicles={showSuggestedVehicles}
      showSuggestedOffenders={showSuggestedOffenders}
      toggleShowSuggestedVehicles={toggleShowSuggestedVehicles}
      toggleShowSuggestedOffenders={toggleShowSuggestedOffenders}
      editInvestigation={editInvestigation}
      toggleEditInvestigation={toggleEditInvestigation}
    />
  );
};

export default ViewCustomer;
