import React from 'react';
import { useParams } from 'react-router-dom';

import View from './ViewInvestigation.view';
import useViewCustomer from './useViewInvestigation';

const ViewCustomer: React.FC = () => {
  const { id } = useParams();

  const {
    addCrimeGroup,
    addDemDocument,
    addDocument,
    addExistingCrimeGroup,
    addExistingIncident,
    addExistingOffender,
    addExistingVehicle,
    addOffender,
    addTodo,
    addVehicle,
    completeTodoVisible,
    crimeGroupIds,
    data,
    demId,
    editCrimeGroupData,
    editInvestigation,
    editOffenderData,
    editVehicleData,
    incidentIds,
    loading,
    offenderIds,
    onAddCrimeGroup,
    onAddExistingCrimeGroup,
    onAddExistingIncident,
    onAddExistingOffenders,
    onAddExistingVehicle,
    onAddExistingVehicles,
    onAddVehicle,
    onCloseInvestigation,
    onCompletedAddOffender,
    onCompletedEditOffender,
    onDeleteCrimeGroup,
    onDeleteDocument,
    onDeleteIncident,
    onDeleteInvestigation,
    onDeleteOffender,
    onDeleteVehicle,
    onEditCrimeGroup,
    onEditVehicle,
    onRefetchInvestigation,
    onReopenInvestigation,
    saving,
    setCompleteTodoVisible,
    setEditCrimeGroupData,
    setEditOffenderData,
    setEditVehicleData,
    setViewTodoVisible,
    showSuggestedOffenders,
    showSuggestedVehicles,
    suggestedOffenders,
    suggestedVehicles,
    takeAllSchemes,
    templatesData,
    templatesLoading,
    toggleAddCrimeGroup,
    toggleAddDemDocument,
    toggleAddDocument,
    toggleAddExistingCrimeGroup,
    toggleAddExistingIncident,
    toggleAddExistingOffender,
    toggleAddExistingVehicle,
    toggleAddOffender,
    toggleAddTodo,
    toggleAddVehicle,
    toggleCloseSuggestedOffenders,
    toggleCloseSuggestedVehicles,
    toggleEditInvestigation,
    toggleShowSuggestedOffenders,
    toggleShowSuggestedVehicles,
    toggleSubscribe,
    updateAddOffenderList,
    updateEditOffenderList,
    updateTodo,
    updateTodoList,
    vehicleIds,
    viewTodoVisible,
  } = useViewCustomer(id || '');

  return (
    <View
      addCrimeGroup={addCrimeGroup}
      addDemDocument={addDemDocument}
      addDocument={addDocument}
      addExistingCrimeGroup={addExistingCrimeGroup}
      addExistingIncident={addExistingIncident}
      addExistingOffender={addExistingOffender}
      addExistingVehicle={addExistingVehicle}
      addOffender={addOffender}
      addTodo={addTodo}
      addVehicle={addVehicle}
      completeTodoVisible={completeTodoVisible}
      crimeGroupIds={crimeGroupIds}
      data={data}
      demId={demId}
      editCrimeGroupData={editCrimeGroupData}
      editInvestigation={editInvestigation}
      editOffenderData={editOffenderData}
      editVehicleData={editVehicleData}
      incidentIds={incidentIds}
      loading={loading}
      offenderIds={offenderIds}
      onAddCrimeGroup={onAddCrimeGroup}
      onAddExistingCrimeGroup={onAddExistingCrimeGroup}
      onAddExistingIncident={onAddExistingIncident}
      onAddExistingOffenders={onAddExistingOffenders}
      onAddExistingVehicle={onAddExistingVehicle}
      onAddExistingVehicles={onAddExistingVehicles}
      onAddVehicle={onAddVehicle}
      onCloseInvestigation={onCloseInvestigation}
      onCompletedAddOffender={onCompletedAddOffender}
      onCompletedEditOffender={onCompletedEditOffender}
      onDeleteCrimeGroup={onDeleteCrimeGroup}
      onDeleteDocument={onDeleteDocument}
      onDeleteIncident={onDeleteIncident}
      onDeleteInvestigation={onDeleteInvestigation}
      onDeleteOffender={onDeleteOffender}
      onDeleteVehicle={onDeleteVehicle}
      onEditCrimeGroup={onEditCrimeGroup}
      onEditVehicle={onEditVehicle}
      onRefetchInvestigation={onRefetchInvestigation}
      onReopenInvestigation={onReopenInvestigation}
      saving={saving}
      setCompleteTodoVisible={setCompleteTodoVisible}
      setEditCrimeGroupData={setEditCrimeGroupData}
      setEditOffenderData={setEditOffenderData}
      setEditVehicleData={setEditVehicleData}
      setViewTodoVisible={setViewTodoVisible}
      showSuggestedOffenders={showSuggestedOffenders}
      showSuggestedVehicles={showSuggestedVehicles}
      suggestedOffenders={suggestedOffenders}
      suggestedVehicles={suggestedVehicles}
      takeAllSchemes={takeAllSchemes}
      templatesData={templatesData}
      templatesLoading={templatesLoading}
      toggleAddCrimeGroup={toggleAddCrimeGroup}
      toggleAddDemDocument={toggleAddDemDocument}
      toggleAddDocument={toggleAddDocument}
      toggleAddExistingCrimeGroup={toggleAddExistingCrimeGroup}
      toggleAddExistingIncident={toggleAddExistingIncident}
      toggleAddExistingOffender={toggleAddExistingOffender}
      toggleAddExistingVehicle={toggleAddExistingVehicle}
      toggleAddOffender={toggleAddOffender}
      toggleAddTodo={toggleAddTodo}
      toggleAddVehicle={toggleAddVehicle}
      toggleCloseSuggestedOffenders={toggleCloseSuggestedOffenders}
      toggleCloseSuggestedVehicles={toggleCloseSuggestedVehicles}
      toggleEditInvestigation={toggleEditInvestigation}
      toggleShowSuggestedOffenders={toggleShowSuggestedOffenders}
      toggleShowSuggestedVehicles={toggleShowSuggestedVehicles}
      toggleSubscribe={toggleSubscribe}
      updateAddOffenderList={updateAddOffenderList}
      updateEditOffenderList={updateEditOffenderList}
      updateTodo={updateTodo}
      updateTodoList={updateTodoList}
      vehicleIds={vehicleIds}
      viewTodoVisible={viewTodoVisible}
    />
  );
};

export default ViewCustomer;
