query listUserNotifications(
  $take: Int
  $skip: Int
  $where: UserNotificationWhereInput
  $orderBy: [UserNotificationOrderByWithRelationInput!]
) {
  listUserNotifications(
    take: $take
    skip: $skip
    where: $where
    orderBy: $orderBy
  ) {
    notifications {
      id
      read
      createdAt
      notification {
        id
        crimeGroupId
        createdAt
        chatId
        body
        articleId
        incidentId
        investigationId
        offenderId
        schemes {
          id
          name
          autoApproveIncidents
          autoApproveOffenders
          restrictIncidentAccess
          defaultPublicOffenderDOB
          userTodos
          userNotifications
          languageCount
          autoPopulateDescription
          logo {
            optimisedPersisted
            id
          }
          darkLogo {
            id
            optimisedPersisted
          }
          imagesRequiredOnOffenders
          goodsMode
          facialRecognition
          taskTimeTracking
        }
        title
        type
        vehicleId
        ban {
          id
          offender {
            id
          }
        }
        userId
      }
    }
    total
  }
}
