query userNotifications(
  $where: UserWhereUniqueInput!
  $orderBy: [UserNotificationOrderByWithRelationInput!]
  $notificationWhere: UserNotificationWhereInput
) {
  user(where: $where) {
    id
    totalNotifications
    totalUnreadNotifications

    notifications(where: $notificationWhere, orderBy: $orderBy) {
      id
      read
      createdAt
      notification {
        id
        crimeGroupId
        createdAt
        chatId
        body
        articleId
        incidentId
        investigationId
        offenderId
        schemes {
          id
          name
          autoApproveIncidents
          autoApproveOffenders
          restrictIncidentAccess
          reportOnly
          defaultPublicOffenderDOB
          userTodos
          userNotifications
          languageCount
          autoPopulateDescription

          logo {
            optimisedPersisted
            id
          }
          darkLogo {
            id
            optimisedPersisted
          }
          members {
            id
            role
          }
          imagesRequiredOnOffenders
          goodsMode
          facialRecognition
          taskTimeTracking
        }
        title
        type
        vehicleId
        ban {
          id
          offender {
            id
          }
        }
        userId
      }
    }
  }
}
