query userNotifications(
  $where: UserWhereUniqueInput!
  $orderBy: [UserNotificationOrderByWithRelationInput!]
  $notificationWhere: UserNotificationWhereInput
  $take: Int
  $skip: Int
) {
  user(where: $where) {
    id
    totalNotifications
    totalUnreadNotifications

    notifications(where: $notificationWhere, orderBy: $orderBy, take: $take, skip: $skip) {
      id
      read
      createdAt
      notification {
        id
        crimeGroupId
        createdAt
        chatId
        body
        articleId
        incidentId
        investigationId
        offenderId
        schemes {
          id
          name
          autoApproveIncidents
          autoApproveOffenders
          restrictIncidentAccess
          reportOnly
          defaultPublicOffenderDOB
          userTodos
          userNotifications
          languageCount
          autoPopulateDescription
          needJustification
          requireSiteNumberForUsers
          oneSelectedIncidentTypeOnly
          logo {
            optimisedPersisted
            id
          }
          darkLogo {
            id
            optimisedPersisted
          }
          members {
            id
            role
          }
          imagesRequiredOnOffenders
          goodsMode
          facialRecognition
          facialDetection
          connectedToSchemes {
            id
            name
          }
          taskTimeTracking
        }
        title
        type
        vehicleId
        ban {
          id
          offender {
            id
          }
        }
        userId
      }
    }
  }
}
