query ActivitiesTableReport(
    $where: TodoRelayWhereInput!
    $orderBy: [TodoOrderByWithRelationInput!]
    $take: Int
    $skip: Int
) {
    todoRelay(where: $where, orderBy: $orderBy, take: $take, skip: $skip) {
        totalCount
        edges {
            node {
                id
                name
                dueDate
                createdAt
                completed
                type
                completedDate
                business {
                    id
                    name
                }
                assignedUsers {
                    id
                    fullName
                }
            }

        }
    }
}
