import type { ExtendedLayout, MetaData } from '../../types';

export const PerformanceMetaData: MetaData[] = [
  { key: 'createdSummary', type: 'summary' },
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'policeSummary', type: 'summary' },
  { key: 'outcomeSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'involvedTagsDonut', type: 'donut' },
  { key: 'goodsTypeDonut', type: 'donut' },
  { key: 'goodsValueDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsHeatMap', type: 'heatmap' },
  { key: 'businessContributionTable', type: 'table' },
  { key: 'topContributors', type: 'table' },
  { key: 'offendersTable', type: 'table' },
  { key: 'crimeGroupTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
];

const PerformanceLayout: ExtendedLayout[] = [
  {
    w: 2,
    h: 4,
    x: 0,
    y: 0,
    minH: 4,
    i: 'createdSummary',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'incidentsSummary',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'policeSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'outcomeSummary',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    minH: 4,
    x: 0,
    y: 0,
    i: 'lossSummary',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 35,
    i: 'pageBreak',
    moved: false,
    static: true,
  },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 74,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 1,
    h: 10,
    maxH: 11,
    x: 0,
    y: 11,
    i: 'crimeTypesDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 11,
    maxH: 11,
    i: 'involvedTagsDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 21,
    maxH: 11,

    i: 'goodsTypeDonut',
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 21,
    maxH: 11,

    i: 'goodsValueDonut',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 34,
    minH: 4,

    i: 'incidentsDayOfWeekGraph',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 17,
    x: 0,
    y: 41,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
  {
    w: 2,
    minW: 2,
    h: 15,
    x: 0,
    y: 48,
    minH: 5,

    i: 'businessContributionTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 56,
    i: 'topContributors',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,

    y: 64,
    minH: 5,

    i: 'offendersTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,

    y: 72,
    minH: 5,

    i: 'crimeGroupTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    minW: 2,

    y: 86,
    minH: 5,

    i: 'targetedBusinessTable',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    minW: 2,

    x: 0,
    y: 92,
    minH: 5,

    i: 'targetedGoodsTable',
    moved: false,
    static: false,
  },
];

export default PerformanceLayout;
