import type { ExtendedLayout, MetaData } from '../../types';

export const PerformanceMetaData: MetaData[] = [
  { key: 'createdSummary', type: 'summary' },
  { key: 'incidentsSummary', type: 'summary' },
  { key: 'policeSummary', type: 'summary' },
  { key: 'investigationSummary', type: 'summary' },
  { key: 'lossSummary', type: 'summary' },
  { key: 'pageBreak', type: 'pageBreak' },
  { key: 'pageBreak2', type: 'pageBreak' },
  { key: 'crimeTypesDonut', type: 'donut' },
  { key: 'involvedTagsDonut', type: 'donut' },
  { key: 'goodsTypeDonut', type: 'donut' },
  { key: 'goodsValueDonut', type: 'donut' },
  { key: 'incidentsDayOfWeekGraph', type: 'graph' },
  { key: 'incidentsHeatMap', type: 'heatmap' },
  { key: 'businessContributionTable', type: 'table' },
  { key: 'topContributors', type: 'table' },
  { key: 'offendersTable', type: 'table' },
  { key: 'crimeGroupTable', type: 'table' },
  { key: 'targetedBusinessTable', type: 'table' },
  { key: 'targetedGoodsTable', type: 'table' },
  { key: 'investigationsTable', type: 'table' },
];

const PerformanceLayout: ExtendedLayout[] = [
  {
    w: 2,
    h: 4,
    x: 0,
    y: 0,
    i: 'createdSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    x: 0,
    y: 4,
    i: 'incidentsSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 12,
    i: 'lossSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  { w: 2, h: 1, x: 0, y: 35, i: 'pageBreak', moved: false, static: true },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 74,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 16,
    i: 'involvedTagsDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 16,
    i: 'goodsTypeDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 9,
    x: 0,
    y: 36,
    i: 'goodsValueDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 45,
    i: 'incidentsDayOfWeekGraph',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 17,
    x: 0,
    y: 57,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 75,
    i: 'businessContributionTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 90,
    i: 'topContributors',
    minW: 2,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 105,
    i: 'offendersTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 120,
    i: 'crimeGroupTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 135,
    i: 'targetedBusinessTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 150,
    i: 'targetedGoodsTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    x: 1,
    y: 4,
    i: 'policeSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 8,
    i: 'outcomeSummary',
    minH: 4,
    moved: false,
    static: false,
  },
];

export const PerformanceDrawerLayout: ExtendedLayout[] = [
  {
    w: 2,
    h: 4,
    x: 0,
    y: 0,
    i: 'createdSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    x: 0,
    y: 4,
    i: 'incidentsSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 12,
    i: 'lossSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  { w: 2, h: 1, x: 0, y: 35, i: 'pageBreak', moved: false, static: true },
  {
    w: 2,
    h: 1,
    x: 0,
    y: 74,
    i: 'pageBreak2',
    moved: false,
    static: true,
  },
  {
    w: 1,
    h: 10,
    x: 1,
    y: 16,
    i: 'involvedTagsDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 10,
    x: 0,
    y: 16,
    i: 'goodsTypeDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 9,
    x: 0,
    y: 36,
    i: 'goodsValueDonut',
    maxH: 11,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 12,
    x: 0,
    y: 45,
    i: 'incidentsDayOfWeekGraph',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 17,
    x: 0,
    y: 57,
    i: 'incidentsHeatMap',
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 75,
    i: 'businessContributionTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 90,
    i: 'topContributors',
    minW: 2,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 105,
    i: 'offendersTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 120,
    i: 'crimeGroupTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 135,
    i: 'targetedBusinessTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 150,
    i: 'targetedGoodsTable',
    minW: 2,
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 15,
    x: 0,
    y: 8,
    i: 'investigationsTable',
    minH: 5,
    moved: false,
    static: false,
  },
  {
    w: 1,
    h: 4,
    x: 1,
    y: 4,
    i: 'policeSummary',
    minH: 4,
    moved: false,
    static: false,
  },
  {
    w: 2,
    h: 4,
    x: 0,
    y: 8,
    i: 'outcomeSummary',
    minH: 4,
    moved: false,
    static: false,
  },

  {
    w: 2,
    h: 4,
    x: 0,
    y: 8,
    i: 'investigationSummary',
    minH: 4,
    moved: false,
    static: false,
  },
];

export default PerformanceLayout;
