import React from 'react';

import View from './AddOffender.view';
import useAddOffender from './useAddOffender';

const AddOffender = (): JSX.Element => {
  const {
    addCustomGallery,
    addExclusion,
    addOffenderTag,
    adminRights,
    ageCheck,
    banData,
    bansData,
    beforeUpload,
    crimeGroupsData,
    customGalleries,
    customGalleriesLoading,
    deleteConfirm,
    documentList,
    documentUploadProps,
    editExclusion,
    editImage,
    fileList,
    form,
    groups,
    groupsLoading,
    idVerified,
    imgChange,
    listVehiclesData,
    loading,
    needJustification,
    offenderSettings,
    onAddCrimeGroup,
    onAddVehicle,
    onCloseFaces,
    onEditImage,
    onRemoveCrimeGroup,
    onRemoveImage,
    onRemoveVehicle,
    onSearchOffender,
    onSelectFace,
    onSubmit,
    onValuesChange,
    potentialOffenders,
    primaryImage,
    reportOnly,
    saving,
    setAgeCheck,
    setBanData,
    setPrimaryImage,
    tags,
    tagsLoading,
    toggleAddCustomGallery,
    toggleAddExclusion,
    toggleAddOffenderTag,
    toggleEditExclusion,
    toggleEditImage,
    toggleViewPotentialOffenders,
    updateExclusion,
    updateNewCustomGalleryData,
    updateNewOffenderTagData,
    uploadFaces,
    uploading,
    vehiclesData,
    viewPotentialOffenders,
  } = useAddOffender();

  return (
    <div>
      <View
        addCustomGallery={addCustomGallery}
        addExclusion={addExclusion}
        addOffenderTag={addOffenderTag}
        adminRights={adminRights}
        ageCheck={ageCheck}
        banData={banData}
        bansData={bansData}
        beforeUpload={beforeUpload}
        crimeGroupsData={crimeGroupsData}
        customGalleries={customGalleries}
        customGalleriesLoading={customGalleriesLoading}
        deleteConfirm={deleteConfirm}
        documentList={documentList}
        documentUploadProps={documentUploadProps}
        editExclusion={editExclusion}
        editImage={editImage}
        fileList={fileList}
        form={form}
        groups={groups}
        groupsLoading={groupsLoading}
        idVerified={idVerified}
        imgChange={imgChange}
        listVehiclesData={listVehiclesData}
        loading={loading}
        needJustification={needJustification}
        offenderSettings={offenderSettings}
        onAddCrimeGroup={onAddCrimeGroup}
        onAddVehicle={onAddVehicle}
        onCloseFaces={onCloseFaces}
        onEditImage={onEditImage}
        onRemoveCrimeGroup={onRemoveCrimeGroup}
        onRemoveImage={onRemoveImage}
        onRemoveVehicle={onRemoveVehicle}
        onSearchOffender={onSearchOffender}
        onSelectFace={onSelectFace}
        onSubmit={onSubmit}
        onValuesChange={onValuesChange}
        potentialOffenders={potentialOffenders}
        primaryImage={primaryImage}
        reportOnly={reportOnly}
        saving={saving}
        setAgeCheck={setAgeCheck}
        setBanData={setBanData}
        setPrimaryImage={setPrimaryImage}
        tags={tags}
        tagsLoading={tagsLoading}
        toggleAddCustomGallery={toggleAddCustomGallery}
        toggleAddExclusion={toggleAddExclusion}
        toggleAddOffenderTag={toggleAddOffenderTag}
        toggleEditExclusion={toggleEditExclusion}
        toggleEditImage={toggleEditImage}
        toggleViewPotentialOffenders={toggleViewPotentialOffenders}
        updateExclusion={updateExclusion}
        updateNewCustomGalleryData={updateNewCustomGalleryData}
        updateNewOffenderTagData={updateNewOffenderTagData}
        uploadFaces={uploadFaces}
        uploading={uploading}
        vehiclesData={vehiclesData}
        viewPotentialOffenders={viewPotentialOffenders}
      />
    </div>
  );
};

export default AddOffender;
