query PerformanceReport($where: SchemeWhereUniqueInput!) {
  scheme(where: $where) {
    id
    name
    incidentsCreated
    messagesSent
    offendersCreated
    updatesCreated
    creationBreakdown {
      data {
        count
        name
      }
      scale
    }
    incidentsByType {
      data
      types
    }
    topContributors {
      id
      fullName
      businesses {
        id
        name
      }
      incidentsCreated
      offendersCreated
      updatesCreated
      messagesSent
    }
  }
}
