query FeedItems(
  $schemeId: String!
  $search: String
  $order: FeedItemOrderByWithRelationInput
  $where: FeedItemWhereInput
  $take: Int
  $skip: Int
  $after: String
  $groups: [String!]
  $groupsWhere2: GroupWhereInput
) {
  listFeedItems(
    where: $where
    schemeId: $schemeId
    search: $search
    order: $order
    take: $take
    skip: $skip
    after: $after
    groups: $groups
  ) {
    feedItems {
      type
      ban {
        endDate
        startDate
        title
        expired
        location
        feedImage {
          ...FeedImage
        }
        offender {
          id
          name
        }
      }
      article {
        id
        title
        createdBy {
          fullName
        }
        image {
          id
          url
          optimised
          position
          rotation
        }
        previewText
        priority
      }
      articleId
      createdAt
      updatedAt
      message
      model
      crimeGroupId
      crimeGroup {
        totalOffenders
        totalIncidents
        alias
        id
        reference
        latestUpdate {
          ...FeedUpdate
        }
      }
      vehicleId
      vehicle {
        totalOffenders
        registration
        reference
        model
        make
        id
        colour
        feedImage {
          ...FeedImage
        }
        latestUpdate {
          ...FeedUpdate
        }
      }
      investigationId
      investigation {
        id
        name
        reference
        totalOffenders
        totalIncidents
        description
        updatedAt
        latestUpdate {
          ...FeedUpdate
        }
      }
      groups(where: $groupsWhere2) {
        id
        name
      }
      id
      incident {
        id
        subject
        reference
        description
        latestUpdate {
          ...FeedUpdate
        }
        approved
        business {
          id
          name
        }
        feedImage {
          ...FeedImage
        }
      }
      incidentId
      offender {
        id
        totalIncidents
        latestIncident {
          id
          dateAgo
          reportedBusinessName
        }
        reference
        updatedAt
        height
        dateOfBirth
        dateSource
        hair
        name
        peculiarities
        race
        approved
        subscribed
        uploaded
        active
        latestUpdate {
          ...FeedUpdate
        }

        feedImage {
          ...FeedImage
        }
      }
      offenderId
    }
    total
  }
}
