query FeedItems(
  $schemeId: String!
  $search: String
  $order: FeedItemOrderByWithRelationInput
  $take: Int
  $skip: Int
  $after: String
  $groups: [String!]
) {
  listFeedItems(
    schemeId: $schemeId
    search: $search
    order: $order
    take: $take
    skip: $skip
    after: $after
    groups: $groups
  ) {
    feedItems {
      type
      article {
        id
        title
        updatedAt
        tags {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
        previewImage
        previewText
        priority
      }
      articleId
      createdAt
      updatedAt
      message
      model
      investigationId
      investigation {
        id
        name
        description
        updatedAt
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
        updates(orderBy: { createdAt: desc }) {
          id
          images {
            id
            optimised
            url
          }
          linkedIncidents {
            id
            subject
            description
            dayTime
            images {
              id
              url
              optimised
            }
          }
          linkedOffenders {
            id
            updatedAt
            name
            images {
              id
              url
              optimised
            }
          }
          text
          type
        }
      }
      groups {
        id
        name
      }
      id
      incident {
        id
        subject
        policeRef
        reference
        description
        dayTime
        date
        totalOffenders
        totalUpdates
        updates(orderBy: { createdAt: desc }) {
          id
          images {
            id
            optimised
            url
          }
          linkedIncidents {
            id
            subject
            description
            dayTime
            images {
              id
              url
              optimised
            }
          }
          linkedOffenders {
            id
            updatedAt
            name
            images {
              id
              url
              optimised
            }
          }
          text
          type
        }
        crimeTypes {
          id
          name
        }
        approved
        business {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
        images(orderBy: { createdAt: desc }) {
          id
          optimised
          url
        }
        groups {
          id
          name
        }
        offenders {
          id
          name
          age
          gender
          race
          dateOfBirth
          build
          images(first: 1) {
            id
            url
            optimised
            card
            offenders {
              id
              name
            }
          }
          recycled
        }
      }
      incidentId
      offender {
        id
        createdAt
        updatedAt
        age
        bans {
          id
          title
          location
          description
          startDate
          endDate
        }
        build
        dateOfBirth
        dateSource
        gender
        hair
        name
        totalIncidents
        totalUpdates
        peculiarities
        race
        approved
        subscribed
        uploaded
        active
        lastActive {
          id
          dayTime
        }
        updates(orderBy: { createdAt: desc }) {
          id
          images {
            id
            optimised
            url
          }
          linkedIncidents {
            id
            subject
            description
            dayTime
            images {
              id
              url
              optimised
            }
          }
          linkedOffenders {
            id
            updatedAt
            name
            images {
              id
              url
              optimised
            }
          }
          text
          type
        }
        images {
          id
          url
          optimised
          card
        }
        tags {
          id
          name
        }
        groups {
          id
          name
        }
        tags {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
          }
        }
        bans {
          id
          title
          location
          description
          startDate
          endDate
        }
        incidents {
          id
          subject
          description
          dayTime
          crimeTypes {
            id
            name
          }
          approved
          location {
            id
            full
          }
          createdBy {
            id
            fullName
            businesses {
              id
              name
            }
          }
          images {
            id
            optimised
          }
        }
      }
      offenderId
    }
    total
  }
}
