fragment FeedImage on Image {
  id
  url
  optimised
  position
  rotation
}

fragment FeedUpdate on Update {
  id
  text
  icon
  type
  createdAt
          feedImage {
          ...FeedImage
        }
  linkedCrimeGroups {
    totalOffenders
    totalIncidents
    alias
    id
    reference
    totalRecoveredValue
    totalTheftSuccess
    totalValue
    updatedAt
  }
  linkedVehicles {
    updatedAt
    totalOffenders
    registration
    reference
    model
    feedImage {
      id
      url
      optimised
      position
      rotation
    }
    make
    id
    colour
  }
  linkedOffenders {
    id
    updatedAt
    age
    build
    height
    dateOfBirth
    name
    race
    gender
    feedImage {
      id
      url
      optimised
      position
      rotation
    }
  }
  linkedIncidents {
    id
    subject
    description
    dayTime
    feedImage {
      id
      url
      optimised
      position
      rotation
    }
  }
  createdBy {
    id
    fullName
    businesses {
      fullName
      id
      name
    }
  }
}



query FeedItems(
  $schemeId: String!
  $search: String
  $order: FeedItemOrderByWithRelationInput
  $where: FeedItemWhereInput
  $take: Int
  $skip: Int
  $after: String
  $groups: [String!]
) {
  listFeedItems(
    where: $where
    schemeId: $schemeId
    search: $search
    order: $order
    take: $take
    skip: $skip
    after: $after
    groups: $groups
  ) {
    feedItems {
      type
      ban {
        endDate
        startDate
        updatedAt
        title
        type
        active
        expired
        id
        location
        description
        feedImage {
          ...FeedImage
        }
        offender {
          id
          name
        }
      }
      article {
        id
        title
        updatedAt
        tags {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            id
            name
            fullName
          }
        }
        image {
          id
          url
          optimised
          position
          rotation
          card
        }
        previewImage
        previewText
        priority
      }
      articleId
      createdAt
      updatedAt
      message
      model
      crimeGroupId
      crimeGroup {
        totalOffenders
        totalIncidents
        totalUpdates
        alias
        id
        reference
        totalRecoveredValue
        totalTheftSuccess
        totalValue
        updatedAt
        latestUpdate {
          ...FeedUpdate
        }
      }
      vehicleId
      vehicle {
        updatedAt
        totalOffenders
        totalUpdates
        registration
        reference
        model
        make
        id
        colour
        feedImage {
          ...FeedImage
        }
        latestUpdate {
          ...FeedUpdate
        }
      }
      investigationId
      investigation {
        id
        name
        reference
        totalOffenders
        totalIncidents
        totalCrimeGroups
        totalUpdates
        description
        updatedAt
        createdBy {
          id
          fullName
          businesses {
            fullName
            id
            name
          }
        }
        latestUpdate {
          ...FeedUpdate
        }
      }
      groups {
        id
        name
      }
      id
      incident {
        id
        subject
        policeRef
        reference
        reference
        description
        dayTime
        date
        totalOffenders
        totalUpdates
        latestUpdate {
          ...FeedUpdate
        }

        crimeTypes {
          id
          name
        }
        approved
        business {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            fullName
            id
            name
          }
        }
        feedImage {
          ...FeedImage
        }
        groups {
          id
          name
        }
      }
      incidentId
      offender {
        id
        createdAt
        reference
        updatedAt
        age
        tags {
          id
          name
        }
        bans {
          id
          title
          location
          description
          startDate
          endDate
        }
        build
        height
        dateOfBirth
        dateSource
        gender
        hair
        name
        totalIncidents
        totalUpdates
        peculiarities
        race
        approved
        subscribed
        uploaded
        active
        lastActive {
          id
          dayTime
        }
        latestUpdate {
          ...FeedUpdate
        }

        feedImage {
          ...FeedImage
        }
        tags {
          id
          name
        }
        groups {
          id
          name
        }
        tags {
          id
          name
        }
        createdBy {
          id
          fullName
          businesses {
            fullName
            id
            name
          }
        }
        bans {
          id
          title
          location
          description
          startDate
          endDate
        }
        incidents {
          id
          subject
          description
          dayTime
          crimeTypes {
            id
            name
          }
          approved
          location {
            id
            full
          }
          createdBy {
            id
            fullName
            businesses {
              fullName
              id
              name
            }
          }
          feedImage {
            ...FeedImage
          }
        }
      }
      offenderId
    }
    total
  }
}
