mutation inviteExistingUser(
  $data: UserUpdateInput!
  $where: UniqueId!
  $groupWhere: GroupWhereInput
) {
  inviteExistingUser(data: $data, where: $where) {
    id
    fullName
    firstLetter
    origName
    origFirstLetter
    email
    publicName
    reportToAllBusinesses
    businesses {
      id
      name
      fullName
    }
    status
    groups(where: $groupWhere) {
      id
      name
    }
    approverGroups {
      id
      name
    }
    loginEvents {
      loginTime
    }
  }
}
