query currentUser(
  $scheme: UniqueId
  $orderBy: [UserSchemeOrderByWithRelationInput!]
) {
  currentUser {
    id
    fullName
    origName
    email
    reference
    demId
    publicName
    reportToAllBusinesses
    notificationCount(scheme: $scheme)
    messageCount
    defaultScheme
    businesses {
      id
      name
      fullName
      demId
      brands
    }
    newUser
    defaultGroups {
      id
      name
      scheme {
        id
      }
    }
    schemes(orderBy: $orderBy) {
      id
      role
      scheme {
        customTranslations
        logo {
          optimisedPersisted
        }
        darkLogo {
          optimisedPersisted
        }
        userTodos
        id
        name
        goodsMode
        autoApproveIncidents
        autoApproveOffenders
        defaultPublicOffenderDOB
        restrictIncidentAccess
        reportOnly
        facialRecognition
        facialDetection
        activityAssignToUser
        useBusinessGroupsOnIncident
        imagesRequiredOnOffenders
        taskTimeTracking
        languageCount
        autoPopulateDescription
        needJustification
        requireSiteNumberForUsers
        oneSelectedIncidentTypeOnly
        connectedToSchemes {
          id
          name
        }
      }
      isAdmin
      permissions {
        model
        allowedMethods
      }
      dashboard {
        runningBanner
        layout {
          h
          i
          maxH
          maxW
          minH
          minW
          moved
          static
          w
          x
          y
        }
      }
    }
    incidentEmail
    incidentPush
    offenderEmail
    offenderPush
    bulletinEmails
    bulletinPush
    messagePush
  }
}
