query InvestigationSuggestions(
  $where: InvestigationWhereUniqueInput!
  $associatedInvestigation: UniqueId
) {
  investigation(where: $where) {
    id
    suggestedOffenders {
      id
      name
      reference
      alias
      dateOfBirth
      age
      gender
      build
      race
      hair
      peculiarities
      totalAssociatedIncidents
      totalAssociatedCrimeGroups
      images {
        id
        optimised
        rotation
        position
      }
      associatedIncidents(associatedInvestigation: $associatedInvestigation) {
        ...IncidentCard
      }
      associatedCrimeGroups(
        associatedInvestigation: $associatedInvestigation
      ) {
        ...CrimeGroups
      }
    }
    suggestedVehicles {
      ...Vehicles
    }
    suggestedIncidents {
      ...IncidentCard
    }
  }
}
