query ViewInvestigation($where: InvestigationWhereUniqueInput!) {
  investigation(where: $where) {
    id
    description
    name
    status
    totalOffenders
    totalIncidents
    totalValue
    totalRecoveredValue
    totalTheftSuccess
    closedAt
    createdBy {
      id
      fullName
    }
    documents {
      id
      name
      url
      thumbnailUrl
      tags {
        name
        id
      }
      articles {
        id
        previewText
        previewImage
      }
    }
    subscribed
    todos {
      ...Todos
    }
    vehicles {
      ...Vehicles
    }
    updates(orderBy: { createdAt: desc }) {
      ...Updates
    }
    crimeGroups {
        id
        alias
        ref
        totalValue
        totalOffenders
        totalIncidents
    }
  }
}
