query ViewInvestigation($where: InvestigationWhereUniqueInput!) {
  investigation(where: $where) {
    id
    description
    name
    totalOffenders
    totalIncidents
    totalValue
    totalRecoveredValue
    totalTheftSuccess
    createdBy {
      id
      fullName
    }
    documents {
      id
      name
      url
      thumbnailUrl
      tags {
        name
        id
      }
    }
    subscribed
    vehicles {
      id
      make
      model
      colour
      registration
      updatedAt
      totalCrimeGroups
      totalOffenders
      totalIncidents
      reference
    }
    updates(orderBy: { createdAt: desc }) {
      id
      text
      type
      createdAt
      images {
        id
        url
        optimised
        optimisedPersisted
        card
        position
      }
      linkedCrimeGroups {
        totalOffenders
        totalIncidents
        alias
        id
        reference
        totalRecoveredValue
        totalTheftSuccess
        totalValue
        updatedAt
      }
      linkedVehicles {
        images {
          id
          url
          optimised
          optimisedPersisted
          position
        }
        updatedAt
        totalOffenders
        registration
        reference
        model
        make
        id
        colour
      }
      linkedIncidents {
        id
        subject
        description
        dayTime
        images {
          id
          url
          optimised
          optimisedPersisted
          position
        }
      }
      linkedOffenders {
        id
        updatedAt
        age
        build
        height
        dateOfBirth
        name
        race
        gender
        images {
          id
          url
          optimised
          optimisedPersisted
          position
        }
      }
      createdBy {
        origName
        id
        fullName
        businesses {
          id
          name
          fullName
        }
      }
      replies {
        id
        text
        type
        createdAt
        images {
          id
          url
          optimisedPersisted
          optimised
          card
          position
        }
        linkedCrimeGroups {
          totalOffenders
          totalIncidents
          alias
          id
          reference
          totalRecoveredValue
          totalTheftSuccess
          totalValue
          updatedAt
        }
        linkedVehicles {
          images {
            id
            url
            optimisedPersisted
            optimised
            position
          }
          updatedAt
          totalOffenders
          registration
          reference
          model
          make
          id
          colour
        }
        linkedIncidents {
          id
          subject
          description
          dayTime
          images {
            id
            url
            optimised
            position
          }
        }
        linkedOffenders {
          id
          updatedAt
          age
          build
          height
          dateOfBirth
          name
          race
          gender
          images {
            id
            url
            optimised
            optimisedPersisted
            position
          }
        }
        createdBy {
          origName
          id
          fullName
          businesses {
            id
            name
            fullName
          }
        }
      }
    }

    offenders {
      id
      name
      reference
      totalIncidents
      age
      gender
      race
      build
      height
      dateOfBirth
      images {
        id
        optimised
        optimisedPersisted
        position
      }
    }
    incidents {
      id
      policeRef
      dayTime
      createdBy {
        organisation
      }
      reference
      subject
      date
      location {
        id
        full
        geoLat
        geoLng
      }
      totalValue
      totalRecoveredValue
    }
    crimeGroups {
      id
      alias
      reference
    }
    flows {
      updatedAt
      name
      id
      description
      edges {
        id
        type
        markerEnd
        source
        sourceHandle
        target
        targetHandle
      }
      nodes {
        id
        type
        data
        height
        width
        style {
          height
          width
        }
        position {
          x
          y
        }
        positionAbsolute {
          x
          y
        }
      }
    }
  }
}
