query ViewInvestigation($where: InvestigationWhereUniqueInput!) {
  investigation(where: $where) {
    id
    description
    name
    status
    totalOffenders
    totalIncidents
    totalValue
    totalRecoveredValue
    totalTheftSuccess
    closedAt
    createdBy {
      id
      fullName
    }
    documents {
      id
      name
      url
      thumbnailUrl
      tags {
        name
        id
      }
      articles {
        id
        previewText
        previewImage
      }
    }
    groups {
      id
      name
    }
    subscribed
    todos {
      ...Todos
    }
    vehicles {
      ...Vehicles
    }
    offenders {
      ...Offenders
      images {
        id
        optimised
        optimisedPersisted
        position
        rotation
        isFace
      }
    }
    incidents(orderBy: { date: desc }) {
      ...Incidents
      business {
        id
        name
      }
      vehicles {
        ...Vehicles
      }
      offenders {
        ...Offenders
        images {
          ...Images
        }
      }
    }
    updates(orderBy: { createdAt: desc }) {
      ...Updates
    }
    crimeGroups {
      ...CrimeGroups
      vehicles {
        ...Vehicles
      }
      offenders {
        ...Offenders

        images {
          ...Images
        }
      }
    }
    flows {
      updatedAt
      name
      id
      description
      edges {
        id
        type
        markerEnd
        source
        sourceHandle
        target
        targetHandle
      }
      nodes {
        id
        type
        data
        height
        width
        style {
          height
          width
        }
        position {
          x
          y
        }
        positionAbsolute {
          x
          y
        }
      }
    }
  }
}
