query WorkflowData(
  $where: SchemeWhereUniqueInput!
  $questionsWhere: QuestionWhereInput
  $schemeTagsWhere: TagWhereInput
  $orderBy: [QuestionOrderByWithRelationInput!]
  $schemeTagsOrderBy: [TagOrderByWithRelationInput!]
) {
  scheme(where: $where) {
    questions(where: $questionsWhere, orderBy: $orderBy) {
      id
      questionOn
      optionsFormFormatted {
        value
        label
      }
      type
      questionFormatted
    }
    schemeTags(where: $schemeTagsWhere, orderBy: $schemeTagsOrderBy) {
      id
      name
    }
    groups {
      id
      name
    }
  }
}
