query OffenderIncidents(
    $where: OffenderWhereUniqueInput!,
    $orderBy: [IncidentOrderByWithRelationInput!],
    $skip: Int,
    $take: Int
) {
    offender(where: $where) {
        incidents(orderBy: $orderBy, skip: $skip, take: $take) {
            id
            reference
            dayTime
            policeRef
            subject
            totalValue
            totalRecoveredValue
            location {
                id
                full
            }
            business {
                id
                name
            }
        }
    }
}
