query QuestionGroupOnScheme($where: SchemeWhereUniqueInput!, $questionGroupsWhere: QuestionGroupWhereInput, $orderBy: [QuestionGroupOrderByWithRelationInput!]) {
  scheme(where: $where) {
    questionGroups(where: $questionGroupsWhere, orderBy: $orderBy) {
      id
      name
      description
      defaultDueDate
      requiredQuestionIds
      questions {
        questionFormatted
        id
        optionsFormFormatted {
          label
          value
        }
        type
      }
    }
  }
}
