import React from 'react';
import { useParams } from 'react-router-dom';

import View from './ViewOffender.view';
import useApproveOffender from './useApproveIncident';
import useViewOffender from './useViewOffender';

const ViewOffender = (): JSX.Element => {
  const offenderId = useParams().id || '';

  const {
    addAddress,
    addBan,
    addCrimeGroup,
    addDocument,
    addExistingVehicle,
    addImages,
    addInvestigation,
    addVehicle,
    associateFilters,
    associatesData,
    associatesLoading,
    closeAddImages,
    confirmDeleteUpdate,
    copyOffender,
    data,
    deleteRights,
    editAddressData,
    editBanData,
    editImageData,
    editImages,
    editOffender,
    editRights,
    editUpdate,
    editUpdateInput,
    editVehicleData,
    generateBulletin,
    handleCreateInvestigation,
    handleEditUpdate,
    handleLinkInvestigation,
    handleUnlinkInvestigation,
    hasConnectedSchemes,
    knowOffender,
    lightBoxOpen,
    linkIncident,
    linkInvestigation,
    linkingInvestigation,
    loadMore,
    loading,
    onAddAddress,
    onAddBan,
    onAddCrimeGroup,
    onAddExistingVehicle,
    onAddUpdateImages,
    onAddUpdateImagesToIncident,
    onAddVehicle,
    onAssociateFilterChange,
    onDelete,
    onDeleteAddress,
    onDeleteBan,
    onDeleteCrimeGroup,
    onDeleteImage,
    onDeleteVehicle,
    onEditAddress,
    onEditBan,
    onEditImage,
    onEditVehicle,
    onSelect,
    onSelectUpdateImages,
    onUpdateImages,
    openLightbox,
    optionRowShow,
    publicOffenderDOB,
    replyTo,
    saving,
    scrolledToTop,
    selectedImages,
    selectedIncidentId,
    setEditAddressData,
    setEditBanData,
    setEditImageData,
    setEditUpdate,
    setEditUpdateInput,
    setEditVehicleData,
    setOptionRowShow,
    setReplyTo,
    shareOpen,
    showAiDrawer,
    showIncidentOptions,
    toggleAddAddress,
    toggleAddBan,
    toggleAddCrimeGroup,
    toggleAddDocument,
    toggleAddExistingVehicle,
    toggleAddInvestigation,
    toggleAddVehicle,
    toggleAiDrawer,
    toggleCopyOffender,
    toggleEditImages,
    toggleEditOffender,
    toggleGenerateBulletin,
    toggleKnowOffender,
    toggleLinkIncident,
    toggleLinkInvestigation,
    toggleSelectImages,
    toggleShareOpen,
    toggleShowIncidentOptions,
    toggleSubscribe,
    toggleViewAssociate,
    toggleViewMatches,
    updateDeleteDocument,
    updateDocumentList,

    updateImagesList,
    updateIncidentList,
    updateInvestigationList,
    userId,
    viewAssociate,
    viewMatches,
  } = useViewOffender(offenderId);
  const { approving, onApprove, onReject } = useApproveOffender({ offenderId });
  return (
    <View
      addAddress={addAddress}
      addBan={addBan}
      addCrimeGroup={addCrimeGroup}
      addDocument={addDocument}
      addExistingVehicle={addExistingVehicle}
      addImages={addImages}
      addInvestigation={addInvestigation}
      addVehicle={addVehicle}
      approving={approving}
      associateFilters={associateFilters}
      associatesData={associatesData}
      associatesLoading={associatesLoading}
      closeAddImages={closeAddImages}
      confirmDeleteUpdate={confirmDeleteUpdate}
      copyOffender={copyOffender}
      data={data}
      deleteRights={deleteRights}
      editAddressData={editAddressData}
      editBanData={editBanData}
      editImageData={editImageData}
      editImages={editImages}
      editOffender={editOffender}
      editRights={editRights}
      editUpdate={editUpdate}
      editUpdateInput={editUpdateInput}
      editVehicleData={editVehicleData}
      generateBulletin={generateBulletin}
      handleCreateInvestigation={handleCreateInvestigation}
      handleEditUpdate={handleEditUpdate}
      handleLinkInvestigation={handleLinkInvestigation}
      handleUnlinkInvestigation={handleUnlinkInvestigation}
      hasConnectedSchemes={hasConnectedSchemes}
      knowOffender={knowOffender}
      lightBoxOpen={lightBoxOpen}
      linkIncident={linkIncident}
      linkInvestigation={linkInvestigation}
      linkingInvestigation={linkingInvestigation}
      loadMore={loadMore}
      loading={loading}
      offenderId={offenderId}
      onAddAddress={onAddAddress}
      onAddBan={onAddBan}
      onAddCrimeGroup={onAddCrimeGroup}
      onAddExistingVehicle={onAddExistingVehicle}
      onAddUpdateImages={onAddUpdateImages}
      onAddUpdateImagesToIncident={onAddUpdateImagesToIncident}
      onAddVehicle={onAddVehicle}
      onApprove={onApprove}
      onAssociateFilterChange={onAssociateFilterChange}
      onDelete={onDelete}
      onDeleteAddress={onDeleteAddress}
      onDeleteBan={onDeleteBan}
      onDeleteCrimeGroup={onDeleteCrimeGroup}
      onDeleteImage={onDeleteImage}
      onDeleteVehicle={onDeleteVehicle}
      onEditAddress={onEditAddress}
      onEditBan={onEditBan}
      onEditImage={onEditImage}
      onEditVehicle={onEditVehicle}
      onReject={onReject}
      onSelect={onSelect}
      onSelectUpdateImages={onSelectUpdateImages}
      onUpdateImages={onUpdateImages}
      openLightbox={openLightbox}
      optionRowShow={optionRowShow}
      publicOffenderDOB={publicOffenderDOB}
      replyTo={replyTo}
      saving={saving}
      scrolledToTop={scrolledToTop}
      selectedImages={selectedImages}
      selectedIncidentId={selectedIncidentId}
      setEditAddressData={setEditAddressData}
      setEditBanData={setEditBanData}
      setEditImageData={setEditImageData}
      setEditUpdate={setEditUpdate}
      setEditUpdateInput={setEditUpdateInput}
      setEditVehicleData={setEditVehicleData}
      setOptionRowShow={setOptionRowShow}
      setReplyTo={setReplyTo}
      shareOpen={shareOpen}
      showAiDrawer={showAiDrawer}
      showIncidentOptions={showIncidentOptions}
      toggleAddAddress={toggleAddAddress}
      toggleAddBan={toggleAddBan}
      toggleAddCrimeGroup={toggleAddCrimeGroup}
      toggleAddDocument={toggleAddDocument}
      toggleAddExistingVehicle={toggleAddExistingVehicle}
      toggleAddInvestigation={toggleAddInvestigation}
      toggleAddVehicle={toggleAddVehicle}
      toggleAiDrawer={toggleAiDrawer}
      toggleCopyOffender={toggleCopyOffender}
      toggleEditImages={toggleEditImages}
      toggleEditOffender={toggleEditOffender}
      toggleGenerateBulletin={toggleGenerateBulletin}
      toggleKnowOffender={toggleKnowOffender}
      toggleLinkIncident={toggleLinkIncident}
      toggleLinkInvestigation={toggleLinkInvestigation}
      toggleSelectImages={toggleSelectImages}
      toggleShareOpen={toggleShareOpen}
      toggleShowIncidentOptions={toggleShowIncidentOptions}
      toggleSubscribe={toggleSubscribe}
      toggleViewAssociate={toggleViewAssociate}
      toggleViewMatches={toggleViewMatches}
      updateDeleteDocument={updateDeleteDocument}
      updateDocumentList={updateDocumentList}
      updateImagesList={updateImagesList}
      updateIncidentList={updateIncidentList}
      updateInvestigationList={updateInvestigationList}
      userId={userId}
      viewAssociate={viewAssociate}
      viewMatches={viewMatches}
    />
  );
};

export default ViewOffender;
