import React from 'react';
import { useParams } from 'react-router-dom';
import View from './ViewOffender.view';
import useViewOffender from './useViewOffender';

const ViewOffender = (): JSX.Element => {
  const offenderId = useParams().id || '';

  const {
    data,
    saving,
    loading,
    openLightbox,
    deleteRights,
    editRights,
    linkIncident,
    toggleLinkIncident,
    updateIncidentList,
    toggleSubscribe,
    confirmDeleteUpdate,
    confirmUpdateImages,
    editUpdate,
    loadMore,
    replyTo,
    scrolledToTop,
    selectedImages,
    setEditUpdate,
    setReplyTo,
    userId,
    addImages,
    addUpdateImages,
    closeAddImages,
    editUpdateInput,
    handleEditUpdate,
    setEditUpdateInput,
    toggleSelectImages,
    lightBoxOpen,
    optionRowShow,
    setOptionRowShow,
    publicOffenderDOB,
    onDelete,
    associatesData,
    associatesLoading,
    onAssociateFilterChange,
    associateFilters,
    toggleViewAssociate,
    viewAssociate,
    toggleViewMatches,
    viewMatches,
    editOffender,
    toggleEditOffender,
    editImages,
    toggleEditImages,
    editImageData,
    setEditImageData,
    onDeleteImage,
    onEditImage,
    onUpdateImages,
    addVehicle,
    addExistingVehicle,
    editVehicleData,
    setEditVehicleData,
    onDeleteVehicle,
    toggleAddVehicle,
    toggleAddExistingVehicle,
    onEditVehicle,
    onAddVehicle,
    onAddExistingVehicle,
    addCrimeGroup,
    onDeleteCrimeGroup,
    toggleAddCrimeGroup,
    onAddCrimeGroup,
    addAddress,
    editAddressData,
    setEditAddressData,
    onDeleteAddress,
    toggleAddAddress,
    onEditAddress,
    onAddAddress,
    addBan,
    editBanData,
    setEditBanData,
    onDeleteBan,
    toggleAddBan,
    onEditBan,
    onAddBan,
  } = useViewOffender(offenderId);

  return (
    <View
      associatesData={associatesData}
      associatesLoading={associatesLoading}
      lightBoxOpen={lightBoxOpen}
      data={data}
      loading={loading}
      saving={saving}
      openLightbox={openLightbox}
      offenderId={offenderId}
      deleteRights={deleteRights}
      editRights={editRights}
      linkIncident={linkIncident}
      toggleLinkIncident={toggleLinkIncident}
      updateIncidentList={updateIncidentList}
      toggleSubscribe={toggleSubscribe}
      confirmDeleteUpdate={confirmDeleteUpdate}
      confirmUpdateImages={confirmUpdateImages}
      editUpdate={editUpdate}
      loadMore={loadMore}
      replyTo={replyTo}
      scrolledToTop={scrolledToTop}
      selectedImages={selectedImages}
      setEditUpdate={setEditUpdate}
      setReplyTo={setReplyTo}
      userId={userId}
      addImages={addImages}
      addUpdateImages={addUpdateImages}
      closeAddImages={closeAddImages}
      editUpdateInput={editUpdateInput}
      handleEditUpdate={handleEditUpdate}
      setEditUpdateInput={setEditUpdateInput}
      toggleSelectImages={toggleSelectImages}
      optionRowShow={optionRowShow}
      setOptionRowShow={setOptionRowShow}
      publicOffenderDOB={publicOffenderDOB}
      onDelete={onDelete}
      onAssociateFilterChange={onAssociateFilterChange}
      associateFilters={associateFilters}
      toggleViewAssociate={toggleViewAssociate}
      viewAssociate={viewAssociate}
      toggleViewMatches={toggleViewMatches}
      viewMatches={viewMatches}
      editOffender={editOffender}
      toggleEditOffender={toggleEditOffender}
      editImages={editImages}
      toggleEditImages={toggleEditImages}
      editImageData={editImageData}
      setEditImageData={setEditImageData}
      onDeleteImage={onDeleteImage}
      onEditImage={onEditImage}
      onUpdateImages={onUpdateImages}
      addVehicle={addVehicle}
      addExistingVehicle={addExistingVehicle}
      editVehicleData={editVehicleData}
      setEditVehicleData={setEditVehicleData}
      onDeleteVehicle={onDeleteVehicle}
      toggleAddVehicle={toggleAddVehicle}
      toggleAddExistingVehicle={toggleAddExistingVehicle}
      onEditVehicle={onEditVehicle}
      onAddVehicle={onAddVehicle}
      onAddExistingVehicle={onAddExistingVehicle}
      addCrimeGroup={addCrimeGroup}
      onDeleteCrimeGroup={onDeleteCrimeGroup}
      toggleAddCrimeGroup={toggleAddCrimeGroup}
      onAddCrimeGroup={onAddCrimeGroup}
      addAddress={addAddress}
      editAddressData={editAddressData}
      setEditAddressData={setEditAddressData}
      onDeleteAddress={onDeleteAddress}
      toggleAddAddress={toggleAddAddress}
      onEditAddress={onEditAddress}
      onAddAddress={onAddAddress}
      addBan={addBan}
      editBanData={editBanData}
      setEditBanData={setEditBanData}
      onDeleteBan={onDeleteBan}
      toggleAddBan={toggleAddBan}
      onEditBan={onEditBan}
      onAddBan={onAddBan}
    />
  );
};

export default ViewOffender;
