mutation updateUser(
  $where: UniqueId!
  $data: UserUpdateInput!
  $groupWhere: GroupWhereInput
  $chatWhere: UserChatWhereInput
  $schemeWhere: UserSchemeWhereInput
) {
  updateUser(where: $where, data: $data) {
    id
    fullName
    email
    organisation
    addresses(where: { primary: { equals: true } }) {
      id
      building
      street
      townCity
      county
      postcode
    }
    disabled
    newUser
    groups(where: $groupWhere) {
      id
      name
    }
    chats(where: $chatWhere) {
      id
      chat {
        name
      }
    }
    schemes(where: $schemeWhere) {
      id
      role
    }
    incidentEmail
    incidentPush
    offenderEmail
    offenderPush
    messagePush
  }
}
