mutation updateOffenderDetails(
  $id: String!
  $alias: OffenderUpdatealiasInput
  $age: NullableEnumAgeFieldUpdateOperationsInput
  $build: NullableEnumBuildFieldUpdateOperationsInput
  $dateOfBirth: NullableSetDateHelper
  $dateSource: NullableSetStringHelper
  $gender: NullableEnumGenderFieldUpdateOperationsInput
  $hair: NullableSetStringHelper
  $name: NullableSetStringHelper
  $peculiarities: NullableSetStringHelper
  $race: NullableEnumRaceFieldUpdateOperationsInput
) {
  updateOffender(
    where: { id: $id }
    data: {
      alias: $alias
      age: $age
      build: $build
      dateOfBirth: $dateOfBirth
      dateSource: $dateSource
      gender: $gender
      hair: $hair
      name: $name
      peculiarities: $peculiarities
      race: $race
    }
  ) {
    id
    alias
    name
    age
    build
    dateOfBirth
    dateSource
    race
    gender
    hair
    peculiarities
    height
    comment
  }
}
