query ListRekMatches($where: RekMatchWhereInput, $skip: Int, $take: Int) {
  listRekMatches(where: $where, skip: $skip, take: $take) {
    total
    matches {
      id
      createdAt
      rekFaceId
      avgSimilarity
      searchedFace {
        boundingHeight
        boundingLeft
        boundingTop
        boundingWidth
        confidence
        id
        image {
          id
          optimised
        }
        qualityBrightness
        qualitySharpness
      }
      matchedFaces {
        id
        similarity
        rekFace {
          id
          boundingHeight
          boundingLeft
          boundingTop
          boundingWidth
          confidence
          qualityBrightness
          qualitySharpness
          image {
            id
            optimised
          }
          offender {
            id
            name
          }
        }
      }
      offender {
        id
        name
      }
    }
  }
}
