import React from 'react';
import View from './AddIncident.view';
import useEditIncident from './useAddIncident';

function EditIncident(): JSX.Element {
  const {
    addExistingCrimeGroup,
    addExistingOffender,
    addExistingVehicle,
    addIncidentTag,
    addNewCrimeGroup,
    addNewVehicle,
    addOffender,
    addRecentOffender,
    assignOffendersToImages,
    beforeUpload,
    crimeGroupsData,
    editCrimeGroupId,
    editOffenderId,
    editVehicleId,
    fileList,
    form,
    groups,
    groupsLoading,
    imgChange,
    listCrimeGroupsData,
    listOffendersData,
    listVehiclesData,
    newImage,
    offenderImgChange,
    offendersData,
    onCancelNewImage,
    onSearchBusiness,
    onSubmit,
    primaryAddress,
    recentOffenderData,
    recentOffenderLoading,
    removeCrimeGroup,
    removeImage,
    removeImageFromOffender,
    removeOffender,
    removeVehicle,
    saving,
    searchOffenders,
    setAddRecentOffender,
    setAssignToImage,
    setEditCrimeGroupId,
    setEditOffenderId,
    setEditVehicleId,
    setSearchOffenders,
    tags,
    tagsLoading,
    toggleAddExistingCrimeGroup,
    toggleAddExistingOffender,
    toggleAddExistingVehicle,
    toggleAddIncidentTag,
    toggleAddNewCrimeGroup,
    toggleAddNewVehicle,
    toggleAddOffender,
    updateCrimeGroupsData,
    updateIncidentTag,
    updateOffender,
    updateOffendersData,
    updateVehiclesData,
    vehiclesData,
  } = useEditIncident();

  return (
    <div>
      <View
        addExistingCrimeGroup={addExistingCrimeGroup}
        addExistingOffender={addExistingOffender}
        addExistingVehicle={addExistingVehicle}
        addIncidentTag={addIncidentTag}
        addNewCrimeGroup={addNewCrimeGroup}
        addNewVehicle={addNewVehicle}
        addOffender={addOffender}
        addRecentOffender={addRecentOffender}
        assignOffendersToImages={assignOffendersToImages}
        beforeUpload={beforeUpload}
        crimeGroupsData={crimeGroupsData}
        editCrimeGroupId={editCrimeGroupId}
        editOffenderId={editOffenderId}
        editVehicleId={editVehicleId}
        fileList={fileList}
        form={form}
        groups={groups}
        groupsLoading={groupsLoading}
        imgChange={imgChange}
        listCrimeGroupsData={listCrimeGroupsData}
        listOffendersData={listOffendersData}
        listVehiclesData={listVehiclesData}
        newImage={newImage}
        offenderImgChange={offenderImgChange}
        offendersData={offendersData}
        onCancelNewImage={onCancelNewImage}
        onSearchBusiness={onSearchBusiness}
        onSubmit={onSubmit}
        primaryAddress={primaryAddress}
        recentOffenderData={recentOffenderData}
        recentOffenderLoading={recentOffenderLoading}
        removeCrimeGroup={removeCrimeGroup}
        removeImage={removeImage}
        removeImageFromOffender={removeImageFromOffender}
        removeOffender={removeOffender}
        removeVehicle={removeVehicle}
        saving={saving}
        searchOffenders={searchOffenders}
        setAddRecentOffender={setAddRecentOffender}
        setAssignToImage={setAssignToImage}
        setEditCrimeGroupId={setEditCrimeGroupId}
        setEditOffenderId={setEditOffenderId}
        setEditVehicleId={setEditVehicleId}
        setSearchOffenders={setSearchOffenders}
        tags={tags}
        tagsLoading={tagsLoading}
        toggleAddExistingCrimeGroup={toggleAddExistingCrimeGroup}
        toggleAddExistingOffender={toggleAddExistingOffender}
        toggleAddExistingVehicle={toggleAddExistingVehicle}
        toggleAddIncidentTag={toggleAddIncidentTag}
        toggleAddNewCrimeGroup={toggleAddNewCrimeGroup}
        toggleAddNewVehicle={toggleAddNewVehicle}
        toggleAddOffender={toggleAddOffender}
        updateCrimeGroupsData={updateCrimeGroupsData}
        updateIncidentTag={updateIncidentTag}
        updateOffender={updateOffender}
        updateOffendersData={updateOffendersData}
        updateVehiclesData={updateVehiclesData}
        vehiclesData={vehiclesData}
      />
    </div>
  );
}

export default EditIncident;
