import React from 'react';
import View from './AddIncident.view';
import useEditIncident from './useAddIncident';

function EditIncident(): JSX.Element {
  const {
    onSubmit,
    saving,
    groups,
    groupsLoading,
    tags,
    tagsLoading,
    primaryAddress,
    addressLoading,
    imgChange,
    fileList,
    beforeUpload,
    addIncidentTag,
    toggleAddIncidentTag,
    updateIncidentTag,
    addOffender,
    toggleAddOffender,
    addExistingOffender,
    toggleAddExistingOffender,
    updateOffendersData,
    offendersData,
    addPreviousLocation,
    toggleAddPreviousLocation,
    updatePreviousLocation,
    addNewLocation,
    toggleAddNewLocation,
    updateNewLocation,
    form,
    recentOffenderData,
    recentOffenderLoading,
    addRecentOffender,
    setAddRecentOffender,
    searchOffenders,
    setSearchOffenders,
    newImage,
    onCancelNewImage,
    assignOffendersToImages,
    setAssignToImage,
    removeImageFromOffender,
    removeImage,
    removeOffender,
    listOffendersData,
    adminRights,
    offenderImgChange,
    editOffenderId,
    setEditOffenderId,
    updateOffender,
    addNewVehicle,
    addExistingVehicle,
    editVehicleId,
    setEditVehicleId,
    toggleAddNewVehicle,
    toggleAddExistingVehicle,
    vehiclesData,
    updateVehiclesData,
    removeVehicle,
    addNewCrimeGroup,
    addExistingCrimeGroup,
    editCrimeGroupId,
    setEditCrimeGroupId,
    toggleAddNewCrimeGroup,
    toggleAddExistingCrimeGroup,
    crimeGroupsData,
    updateCrimeGroupsData,
    removeCrimeGroup,
    listVehiclesData,
    listCrimeGroupsData,
  } = useEditIncident();

  return (
    <div>
      <View
        updateOffender={updateOffender}
        editOffenderId={editOffenderId}
        setEditOffenderId={setEditOffenderId}
        addExistingOffender={addExistingOffender}
        addIncidentTag={addIncidentTag}
        addNewLocation={addNewLocation}
        addOffender={addOffender}
        addPreviousLocation={addPreviousLocation}
        addressLoading={addressLoading}
        beforeUpload={beforeUpload}
        fileList={fileList}
        form={form}
        groups={groups}
        groupsLoading={groupsLoading}
        imgChange={imgChange}
        offendersData={offendersData}
        onSubmit={onSubmit}
        saving={saving}
        primaryAddress={primaryAddress}
        recentOffenderData={recentOffenderData}
        recentOffenderLoading={recentOffenderLoading}
        addRecentOffender={addRecentOffender}
        setAddRecentOffender={setAddRecentOffender}
        tags={tags}
        tagsLoading={tagsLoading}
        toggleAddExistingOffender={toggleAddExistingOffender}
        toggleAddIncidentTag={toggleAddIncidentTag}
        toggleAddNewLocation={toggleAddNewLocation}
        toggleAddOffender={toggleAddOffender}
        toggleAddPreviousLocation={toggleAddPreviousLocation}
        updateIncidentTag={updateIncidentTag}
        updateNewLocation={updateNewLocation}
        updateOffendersData={updateOffendersData}
        updatePreviousLocation={updatePreviousLocation}
        searchOffenders={searchOffenders}
        setSearchOffenders={setSearchOffenders}
        newImage={newImage}
        assignOffendersToImages={assignOffendersToImages}
        onCancelNewImage={onCancelNewImage}
        setAssignToImage={setAssignToImage}
        removeImageFromOffender={removeImageFromOffender}
        removeImage={removeImage}
        removeOffender={removeOffender}
        adminRights={adminRights}
        listOffendersData={listOffendersData}
        offenderImgChange={offenderImgChange}
        addNewVehicle={addNewVehicle}
        addExistingVehicle={addExistingVehicle}
        editVehicleId={editVehicleId}
        setEditVehicleId={setEditVehicleId}
        toggleAddNewVehicle={toggleAddNewVehicle}
        toggleAddExistingVehicle={toggleAddExistingVehicle}
        vehiclesData={vehiclesData}
        updateVehiclesData={updateVehiclesData}
        removeVehicle={removeVehicle}
        removeCrimeGroup={removeCrimeGroup}
        addNewCrimeGroup={addNewCrimeGroup}
        addExistingCrimeGroup={addExistingCrimeGroup}
        editCrimeGroupId={editCrimeGroupId}
        setEditCrimeGroupId={setEditCrimeGroupId}
        toggleAddNewCrimeGroup={toggleAddNewCrimeGroup}
        toggleAddExistingCrimeGroup={toggleAddExistingCrimeGroup}
        crimeGroupsData={crimeGroupsData}
        updateCrimeGroupsData={updateCrimeGroupsData}
        listVehiclesData={listVehiclesData}
        listCrimeGroupsData={listCrimeGroupsData}
      />
    </div>
  );
}

export default EditIncident;
