mutation updateVehicle($where: UniqueId!, $data: VehicleUpdateInput!) {
  updateVehicle(where: $where, data: $data) {
    id
    make
    model
    registration
    reference
    totalOffenders
    totalIncidents
    images {
      id
      optimised
      url
      position
      rotation
      policeImage
      rotation
      primary
    }
    customGalleries {
      id
      name
    }
    groups {
      id
      name
    }
    incidents {
      id
      subject
    }
    offenders {
      id
      name
    }
    updatedAt
    colour
    crimeGroup {
      id
      reference
    }
  }
}
